### ISSUE TITLE
单窗口显示模式下，点击关注的UP主页，存在重叠Bug

### ISSUE THREAD

**Issue by doufuru007** [ywmoyue/biliuwp-lite#100]
单窗口显示模式下，在首页点击个人头像，点击关注的UP，进入其主页后，会出现关注列表和UP空间主页重叠

**Comment by ywmoyue** [comment]
能否截图一下看看什么情况

**Comment by doufuru007** [comment]
（1）显示模式选择单窗口

（2）在首页左上角点开关注


（3）随便点一个UP主，进个人主页

（4）与上一页面重叠Bug


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ywmoyue/biliuwp-lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ywmoyue/biliuwp-lite] 单窗口显示模式下，点击关注的UP主页，存在重叠Bug (Issue #100)





 
能否截图一下看看什么情况

**Comment by doufuru007** [comment]
> 能否截图一下看看什么情况

![屏幕截图(4)](https://github.com/ywmoyue/biliuwp-lite/assets/128572283/01cd5446-cbad-4ab2-b497-21bfd5fb1b29)

**Comment by doufuru007** [comment]
> 能否截图一下看看什么情况
点击UP头像，进入投稿主页，随便点击一个视频播放，也会发生重叠
![屏幕截图(10)](https://github.com/ywmoyue/biliuwp-lite/assets/128572283/1b679072-2fc6-47b1-9dac-47586f6aa473)

**Comment by TPAXcc** [comment]
好家伙

**Comment by ywmoyue** [comment]
没见过的bug，你试试应用商店上下个WinUI Gallery看看里面的控件啥的是不是也是这样的情况
