### ISSUE TITLE
低宽度情况下评论区部分元素会冲突

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#102]
![图片](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/f9a7d111-41be-4b9c-9d28-c86206ec39a1)
感觉低宽度可以改成图片里的样式
另外 评论/点赞数 > 三位数时可以直接四舍五入，比如:
```
like:129 显示为 129
like:2353 显示为 2.4k
like:46945 显示为 4.7w
like:989763 显示为 99w
```
然后悬停在评论/点赞按钮上时弹出详细数据，如下图
![图片](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/8cf7875a-1e63-48ad-b7cb-cd6def135fb2)
(有点抽象，希望能看懂
这样就既容易显示也方便查看详细数据

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/d7ef8767-6a63-455f-a65b-2f60ebdafa25)
这样做感觉怪怪的
