### ISSUE TITLE
4.6.1版本中键点击视频关闭页面失效

### ISSUE THREAD

**Issue by hoilc** [ywmoyue/biliuwp-lite#121]
中键点击标签页或侧栏仍能关闭页面

**Comment by CKopoer** [comment]
侧键关闭页面也一样，如果鼠标指在视频范围内是无法关闭页面的，必须指在视频画面外。最新版改动了这部分吗？

**Comment by ywmoyue** [comment]
> 侧键关闭页面也一样，如果鼠标指在视频范围内是无法关闭页面的，必须指在视频画面外。最新版改动了这部分吗？

因为调整手势对视频画面元素做了调整，我修复一下
