### ISSUE TITLE
按住倍速播放能否改为右方向键

### ISSUE THREAD

**Issue by CKopoer** [ywmoyue/biliuwp-lite#139]
由于鼠标按住拖动会调整视频进度，目前按住鼠标倍速播放必须保持鼠标不动，长时间保持这个姿势比较别扭。能不能像目前官方客户端一样改成按住键盘右方向键3.0x倍速播放呢，感谢大佬

还有一点就是目前倍速播放时提示文字显示在画面正中心，可能改成画面正上方会好点？

**Comment by CKopoer** [comment]
目前这个项目有交流群吗

**Comment by ywmoyue** [comment]
> 目前这个项目有交流群吗

没有群，暂不打算搞群
