### ISSUE TITLE
没有弹幕显示，视频窗口会弹出来“程序出现一个错误，已记录”

### ISSUE THREAD

**Issue by ikhblo** [ywmoyue/biliuwp-lite#140]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/67190477/a2334aff-4baf-4945-8610-f7babc3fe75e)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/67190477/b94df0e9-6227-486b-8ce2-110eaaac60cd)

但并不影响视频的播放，只是单纯没弹幕

**Comment by ywmoyue** [comment]
我开着代理的时候好像也会出现这种情况，可能是网络问题？

**Comment by ikhblo** [comment]
我重新安装后就好了，感觉设置不能改动太多次，我第一次改动太多次设置就有各种各样的问题

**Comment by ywmoyue** [comment]
那这个Issue我关闭了
