### ISSUE TITLE
视频无法播放 页面加载为空白 “网络请求出现错误（GET）”

### ISSUE THREAD

**Issue by WinXS** [ywmoyue/biliuwp-lite#143]
<img width="576" alt="Snipaste_2023-05-30_15-56-11" src="https://github.com/ywmoyue/biliuwp-lite/assets/29294841/ffef4a86-6bfa-41e1-91b1-b661a180a09f">

**Comment by ywmoyue** [comment]
请通过邮箱发送一下出现问题的日志

**Comment by ywmoyue** [comment]
超过一个月未回复或未通过邮箱发送日志，此issue关闭，后续再出现同类问题请新建Discussion讨论贴并引用此issue
