### ISSUE TITLE
用户主页搜索视频提示访问权限不足

### ISSUE THREAD

**Issue by PIut02** [ywmoyue/biliuwp-lite#151]
无法正常搜索
版本为4.6.2.0

**Comment by ywmoyue** [comment]
请把日志通过邮件发送给我

**Comment by PIut02** [comment]
日志在附件里了






                       
原始邮件
                       
                     

发件人："ywmoyue"< ***@***.*** &gt;;

发件时间：2023/6/9 20:40

收件人："ywmoyue/biliuwp-lite"< ***@***.*** &gt;;

抄送人："Pluto"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ywmoyue/biliuwp-lite] 用户主页搜索视频提示访问权限不足 (Issue #151)




 
请把日志通过邮件发送给我
