### ISSUE TITLE
直播弹幕服务器无法连接

### ISSUE THREAD

**Issue by muzinicemoon** [ywmoyue/biliuwp-lite#154]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/34019015/4f1f5e70-600d-4489-bdb2-ceb145087322)
点进任意直播间均无法连接弹幕服务器，显示“连接失败:Unable to connect to the remote server ”

**Comment by ywmoyue** [comment]
请将日志通过邮件发送给我

**Comment by ywmoyue** [comment]
从日志上没看出问题，是毕现还是偶现，之前有出现过吗，有条件的话可以试一下这个项目的直播能否正常观看：https://github.com/xiaoyaocz/AllLive

**Comment by muzinicemoon** [comment]
> 

从下载使用本项目开始到现在两个礼拜左右是必现的，但是今天试了试又正常了，感谢您回复~~
