### ISSUE TITLE
顶部 Tab 宽度加载时和加载后能不能固定

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#158]
加载时
![图片](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/c6d10039-54bd-42b5-bf97-a6fddc4cbf6a)
加载后
![图片](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/28415477-176e-41be-a4e1-9a903f1d59db)

**Comment by TPAXcc** [comment]
Tab 空间不够时压缩可以理解，但是加载时没必要吧，或者说是不是应该保持加载时与加载后的宽度一致？

**Comment by ywmoyue** [comment]
长度固定问题同这个issue，4.7.2之后可以测一下
 https://github.com/ywmoyue/biliuwp-lite/issues/721


![image](https://github.com/user-attachments/assets/a959e6fd-d428-4669-85df-f96cce96c378)
