### ISSUE TITLE
播放列表与稍后再看存在冲突，能否考虑将播放列表位置挪到视频详情页下部

### ISSUE THREAD

**Issue by CKopoer** [ywmoyue/biliuwp-lite#160]
如图所示，并将自动连续播放视频的优先级设为优先播放播放列表下一视频
![image](https://github.com/ywmoyue/biliuwp-lite/assets/52709412/f5cec189-91d6-4452-b17a-8a92afb3ccea)

**Comment by ywmoyue** [comment]
不好做，这不是分p，切换的时候是要重刷整个页面的，放到详情里面我感觉效果不好

**Comment by CKopoer** [comment]
> 不好做，这不是分p，切换的时候是要重刷整个页面的，放到详情里面我感觉效果不好

官方客户端是类似处理方式，不过稍后再看做成了可以点击，隐藏在上方
![image](https://github.com/ywmoyue/biliuwp-lite/assets/52709412/db207357-17c3-4265-9045-5850bf3811e4)

**Comment by ywmoyue** [comment]
行，我有空看一下

**Comment by ywmoyue** [comment]
@CKopoer 麻烦测一下，这个临时版本处理了冲突问题 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 可以再测一下

> 如果某个视频存在播放列表，当点击下一个稍后再看列表内的视频时，播放列表不会被更新

这个问题没想到什么好的解决方式，因为有的视频的合集中可能不会包含该视频，不能说检测到一个播放列表中没有该视频就把它关了，比如BV1CT4m1S7Ve有5个合集但是只有一个合集有该视频

临时解决方式是加了一个右键手动关闭该播放列表的功能

**Comment by ywmoyue** [comment]
没有回复，我这边就先发版本了，有问题下个版本再处理
