### ISSUE TITLE
弹幕加载问题

### ISSUE THREAD

**Issue by yishuoVC** [ywmoyue/biliuwp-lite#162]
弹幕加载数量只有200~400条，几千条弹幕的视频也是这样

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/65c4ce4b-e549-4aaa-a0f0-c5f2a61bbafb)
怎么看出得只加载了几百条弹幕

**Comment by yishuoVC** [comment]
![屏幕截图(59)](https://github.com/ywmoyue/biliuwp-lite/assets/106026621/f8043d11-376c-4f44-b818-7e1fff13af0f)
在弹幕设置当中显示的，弹幕数量与实际相差甚远

**Comment by ywmoyue** [comment]
biliLite-uwp使用旧版的xml弹幕接口，b站官方已更换protobuf弹幕接口

参考https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/danmaku/danmaku_proto.md

**Comment by xiaoyaocz** [comment]
这个弹幕数量显示不准确的，弹幕是按每6分钟一段进行加载，显示的数量是这6分钟内的弹幕数量
