### ISSUE TITLE
4.6.3 评论请求错误(已解决)

### ISSUE THREAD

**Issue by CoderYiXin** [ywmoyue/biliuwp-lite#166]

**Comment by Shaddoll126** [comment]
同款问题,不单独开一个楼了XD

**Comment by JiayanJohnnyChu** [comment]
一样的问题

**Comment by ywmoyue** [comment]
官方接口换了

**Comment by 2316778816** [comment]
昨天下午官方突然换接口了，我以为我网络问题搞了半天路由器

**Comment by Shaddoll126** [comment]
现在能看到评论区了!

**Comment by ywmoyue** [comment]
> 现在能看到评论区了!

啊这，确实，那我不处理了，或者加个替代方案，请求失败就改用新接口

**Comment by ywmoyue** [comment]
> 不懂，阿B总换接口是为了啥呢，程序员闲着没事干吗

https://www.bilibili.com/read/cv23920810?spm_id_from=333.999.list.card_opus.click 啊B重构呢，盲猜这波重构完biliRoaming可能要寄
