### ISSUE TITLE
希望能更改新标签页的背景

### ISSUE THREAD

**Issue by Clement-WANGWH** [ywmoyue/biliuwp-lite#188]
新标签页的图片太花，看不清其中的文本内容

**Comment by crepassob** [comment]
这个可以在新标签页右上角菜单的自定义背景中，自己换一张背景图片解决
![图片](https://github.com/ywmoyue/biliuwp-lite/assets/42341537/5bfc028a-b9b4-47e6-99a5-921c27251e73)
