### ISSUE TITLE
4.6.6.0 个别直播无法播放

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#189]
显示 bvc-play-url-one 出错.
查看了日志, 但是显示GET请求一切正常. 无报错.

查看了一下, 现在调用这个api时会返回错误的信息: 
https://api.live.bilibili.com/room/v1/Room/playUrl?cid=7902350&qn=10000&platform=web

`
{"code":19001012,"message":"调用bvc-play-url-one出错","ttl":1,"data":{"current_quality":0,"accept_quality":null,"current_qn":0}}
`

应该是b站修改了api导致的. 希望能有方法尽快修复.

**Comment by GD-Slime** [comment]
测试了一下, 应该这个api还是可用的:
https://github.com/SocialSisterYi/bilibili-API-collect/blob/21c7f54e0519b10a8e00edb88d11caa470683571/docs/live/info.md#%E8%8E%B7%E5%8F%96%E7%9B%B4%E6%92%AD%E9%97%B4%E4%BF%A1%E6%81%AF-1

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/660e00bf-7a2c-4317-bd81-39ea74782902)

应该是个别直播无法播放，我看了下除了你那个直播外的其他直播是正常的

**Comment by GD-Slime** [comment]
> ![image](https://user-images.githubusercontent.com/28388300/251099379-660e00bf-7a2c-4317-bd81-39ea74782902.png)
> 
> 应该是个别直播无法播放，我看了下除了你那个直播外的其他直播是正常的

确实, 我也发现了. 只有这个直播间无法获取, 其余直播间可以进去.

**Comment by GD-Slime** [comment]
发现: `https://api.live.bilibili.com/room/v1/Room/playUrl` 这个本项目用的api现在无法获取这些直播间的直播流;

b站网页端现在所用的: `https://api.live.bilibili.com/xlive/web-room/v1/index/getRoomPlayInfo` 也无法获取直播流(b站估计自己也没发现...);
b站网页端在api无法获取直播流后, 应该是回落到使用html内嵌的直播流. 

这个直播流可以用`https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo`来获取, 但是格式和上面两个api返回的不太一样.

**Comment by GD-Slime** [comment]
Fixed in #194 . 等待合并.
