### ISSUE TITLE
[BUG]打开图片会卡死

### ISSUE THREAD

**Issue by 6uu1** [ywmoyue/biliuwp-lite#200]
打开评论区的图片后主界面会卡死，需要关闭再重新打开才可以正常使用

**Comment by 6uu1** [comment]
> 1.哪个视频底下哪个评论图片，发一下视频bv号 2.请把日志文件通过邮箱发送给我，日志文件在应用帮助页最下面能找到，邮箱在应用关于页能找到

感谢回复！
其实是每个评论的图片都是这样子，比如 [【晚上加班但小家伙不睡】体验卡](https://b23.tv/BV1PP411y7Rn)  里面的这个
![image](https://github.com/ywmoyue/biliuwp-lite/assets/122669698/33bd5bb0-fba5-4c53-b34c-4ff007359618)
日志稍后发送

**Comment by ywmoyue** [comment]
已收到日志，问下是启用了新窗口打开图片吗

**Comment by 6uu1** [comment]
> 已收到日志，问下是启用了新窗口打开图片吗

是的
