### ISSUE TITLE
在已经播放一个视频下的情况下播放下一个视频导致的错误

### ISSUE THREAD

**Issue by 360memz-bit** [ywmoyue/biliuwp-lite#201]
在已经播放一个视频下的情况下播放下一个视频后，窗口上显示的视频的标题是下一个视频的标题，但视频内容正常
有的时候就是播放的视频是下一个的详情和标题 但视频是上一个的 音频又是正在放的视频的（如果退出重进会好，但是再换别的视频依然会这样）
![QQ截图20230712001227](https://github.com/ywmoyue/biliuwp-lite/assets/67247759/28948dc5-3fe1-4a2d-a20f-cd26f8e337f1)
如图

**Comment by ywmoyue** [comment]
单窗口模式多次进入视频的bug，有空看看
