### ISSUE TITLE
无法登录账号、搜索错误

### ISSUE THREAD

**Issue by schwarzent** [ywmoyue/biliuwp-lite#221]
用二维码扫码登录和密码登录都会显示账号未登录
搜索时会提示网络请求错误，无法搜索
但是视频能正常播放

**Comment by ywmoyue** [comment]
我这一切正常
1. 请排查是否开了系统代理
2. 请将日志通过邮箱发送给我，邮箱地址在应用的关于页能找到

**Comment by ywmoyue** [comment]
看日志很怪，我需要添加一些日志输出看是哪里出的问题

以及，你这边是否尝试过卸载应用后使用[安装教程](https://github.com/ywmoyue/biliuwp-lite/blob/dev/document/install-readme.md)里的脚本方式安装

**Comment by ywmoyue** [comment]
请在更新4.6.10后在设置的其他tab中将日志级别设为Trace，重新操作一次登录账号和搜索，然后再发送日志到我邮箱

**Comment by schwarzent** [comment]
更新之后已经可以登录
