### ISSUE TITLE
首页点击视频错误跳转

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#233]
今天上午出现好几次了,点击视频后跳转至9bishi的上古测试视频不知道是不是新出炉的bug

**Comment by hifengthis** [comment]
我会跳到一个字幕君交流场所的视频

**Comment by Shaddoll126** [comment]
那看来并非个例了    那个就是9bishi早期测试弹幕系统的视频

**Comment by ywmoyue** [comment]
视频链接处理规则有问题，发现视频链接中有参数follow_av2会导致解析出的av号为2
