### ISSUE TITLE
扫码登录账号后，点击个人中心，出现一个未处理错误

### ISSUE THREAD

**Issue by abandonstudy** [ywmoyue/biliuwp-lite#251]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/94209629/4bd8d52c-908c-4263-8492-eb64fdc00a6b)
日志
[20230809.log](https://github.com/ywmoyue/biliuwp-lite/files/12300637/20230809.log)
是不是因为我这个账号没有发过视频的原因

**Comment by FeetingTime** [comment]
一样

**Comment by ywmoyue** [comment]
@abandonstudy @FeetingTime 查看正常有投稿视频的up主的个人中心是否正常

**Comment by abandonstudy** [comment]
> @abandonstudy @FeetingTime查看正常 有投稿视频的up主的个人中心是否正常

只有自己查看不了，别的up都是可以的

**Comment by ywmoyue** [comment]
更新到4.6.12是否还会出现这个报错 @abandonstudy

**Comment by abandonstudy** [comment]
> 更新到4.6.12是否还会出现这个报错 @abandonstudy

问题已解决

**Comment by abandonstudy** [comment]
Thanks♪(･ω･)ﾉ
