### ISSUE TITLE
“动态”里的“追番追剧”显示不出来

### ISSUE THREAD

**Issue by xueshanqiu** [ywmoyue/biliuwp-lite#269]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/111494203/858b07bf-258a-4e30-b8a1-cae274eb694e)

**Comment by GD-Slime** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/287ee6f2-2d00-4c11-bbec-3bb84456a411)

看了一下，应该是这个api被b站弃用了，需要从网页端抓个新的api

**Comment by ywmoyue** [comment]
@GD-Slime 用户动态这块我正在调整代码，调整完代码后再和视频动态一样处理
