### ISSUE TITLE
直播间人气以及弹幕错误

### ISSUE THREAD

**Issue by RicardoDENG** [ywmoyue/biliuwp-lite#300]
1.点进直播间人气会变为1
2.直播间大部分弹幕获取不到，只能断断续续获取少部分弹幕
![AUT~ S U} ROKST%4~QKS%4](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/46ba021b-bb9e-456e-b575-a4d36a214ab1)
最新版4.16.13且采用power shell安装

**Comment by GD-Slime** [comment]
人气的话好像之前b站改了很多次……
弹幕问题的话是b站近期加了反爬措施，目前很多弹幕站都有获取不了弹幕的问题。

**Comment by GD-Slime** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/208d7b11-7d13-4fe3-b2b3-ab44988a1b9c)
试着修了一下，但感觉还是相比于网页端少了不少

**Comment by RicardoDENG** [comment]
我发现刷新三次直播间弹幕貌似就正常了，但是要保持在线，退出后重进又没了

**Comment by GD-Slime** [comment]
#303 我修了一下，但是好像还是不能接收全……需要更多测试
@RicardoDENG 如果可以的话，可以先下载源码编译一下试试是否可用

**Comment by RicardoDENG** [comment]
> #303 我修了一下，但是好像还是不能接收全……需要更多测试 @RicardoDENG 如果可以的话，可以先下载源码编译一下试试是否可用

抱歉，我没有编程基础，只能辛苦大佬您了@GD-Slime，加油(ง •_•)ง

**Comment by GD-Slime** [comment]
人气的话参考 https://github.com/SocialSisterYi/bilibili-API-collect/issues/809 应该是已经被弃用了
目前只能禁止人气值更新，当然，这个值如果不刷新直播间就不会变了
