### ISSUE TITLE
个别视频打开评论后无响应

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#302]
BV1RS4y117P4 开启长评论折叠后打开评论无响应

**Comment by GD-Slime** [comment]
奇怪 我这里没有复现

**Comment by ywmoyue** [comment]
我设置评论长度80后出现的，可能有什么特殊内容发生截断了

**Comment by GD-Slime** [comment]
> 我设置评论长度80后出现的，可能有什么特殊内容发生截断了 @GD-Slime

复现了 应该是有什么东西被截断了

**Comment by GD-Slime** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/e30edf79-9b72-4f04-b0f5-59a478290c39)
调整为79后没有卡死了，同时这个评论发生了折叠。是否是这个评论的问题？

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/issues/302#issuecomment-1705909102

行，我晚上看一下

**Comment by GD-Slime** [comment]
> [#302 (comment)](https://github.com/ywmoyue/biliuwp-lite/issues/302#issuecomment-1705909102)
> 
> 行，我晚上看一下

调到83也会一样卡死，看来一般就是多个emoji堆积造成的了
