### ISSUE TITLE
最新版直播弹幕完全消失

### ISSUE THREAD

**Issue by thouser8** [ywmoyue/biliuwp-lite#314]
如图，最新版直播弹幕显示连接成功后一个也没有![{190B6280-BD99-48c1-8260-92F0D87EEEF7}.png](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/358858fd-c0b0-4ed9-8a19-0b9e2c268c7a)

**Comment by ywmoyue** [comment]
打包release后出现的问题，Brotli库没被打包进去 (；′⌒`)
