### ISSUE TITLE
下载组件在选择优先下载格式时报错

### ISSUE THREAD

**Issue by RainingLight** [ywmoyue/biliuwp-lite#336]
### Bug 描述

在海外点开下载按键或切换优先下载格式时，应用会显示报错，此时下载视频会弹出提示“object reference not set to an instance”.

### 操作步骤

```plain text
1.打开应用
2.选中任何视频
3.点击下载键或在之后切换优先下载格式，会导致报错
4.此时下载视频，相应分P变为“object reference not set to an instance”
```

### 期望结果

可以正常下载

### 截图

![屏幕截图 2023-10-04 210547](https://github.com/ywmoyue/biliuwp-lite/assets/146957020/44028224-b334-4197-ba15-704e33fb4df7)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by RainingLight** [comment]
截图展示视频bv号为BV1yx41127Zo

**Comment by RainingLight** [comment]
与[issues/335](github.com/ywmoyue/biliuwp-lite/issues/335)情况相似，但不同的是该视频可以正常播放

**Comment by ywmoyue** [comment]
确认了下和 #335 是同一个问题，这个视频的18p和20p没有dash链接只有flv链接
