### ISSUE TITLE
直播中心-佩戴中心需要重新登录

### ISSUE THREAD

**Issue by Jiagu1218** [ywmoyue/biliuwp-lite#354]
### Bug 描述

直播中心-佩戴中心需要重新登录

### 操作步骤

```plain text
打开 直播-关注的直播-查看全部-佩戴中心
```

### 期望结果

账号正常登录，无需重新登录

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 设备类型

笔记本

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
有时打开专栏也会有这样的问题，显示未登录。 应该是同一个问题？

**Comment by Jiagu1218** [comment]
> 有时打开专栏也会有这样的问题，显示未登录。 应该是同一个问题？

电脑上的开发环境删了，不确定
