### ISSUE TITLE
4.6.17没有 new_version.json

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#362]
### Bug 描述

本项目master/docment/new_version.json 没有为4.6.17更新 导致使用旧版的用户无法收到更新通知

### 操作步骤

```plain text
打开本项目master/docment/new_version.json 仍为4.6.16的说明
```

### 期望结果

更新为4.6.17

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
昨天忘了，我今天晚上有空改下
