### ISSUE TITLE
直播间标题不显示，点击右边主播栏会闪退

### ISSUE THREAD

**Issue by RicardoDENG** [ywmoyue/biliuwp-lite#378]
### Bug 描述

直播间标题不显示，点击右边主播栏会闪退

### 操作步骤

```plain text
左上角直播标题不显示，点击右边箭头这个地方会闪退
```

### 期望结果

左上角正常显示直播间标题，点击主播不会闪退

### 截图

![QKRF5P MKMA59R)EA8 %1(O](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/10d4c455-d74a-465e-9e20-129631bc65b3)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 10 21H1 (Build 19043)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
最新dev编译，
直播间标题未出现 复现成功，
点击“主播”按钮闪退 未复现成功。

您是否还在使用4.6.18版本？ 如果是该版本的话可能在直播方面有bug，建议可以等一会发布的4.6.19版本。

**Comment by ywmoyue** [comment]
@GD-Slime  点击主播按钮闪退我这边复现了，试了下应该是部分直播间会出现

**Comment by RicardoDENG** [comment]
貌似大主播的荣耀较多较多会闪退，小主播不会

**Comment by ywmoyue** [comment]
我可能找到问题了，现在有些主播数据中的jumpUrl不是合法的url，导致页面渲染炸了
