### ISSUE TITLE
一次意外关机重启后 App 在启动界面闪退

### ISSUE THREAD

**Issue by ChiotOnAGE** [ywmoyue/biliuwp-lite#381]
### Bug 描述

App 在启动页面停留一分多钟后闪退，触发 Hanging Event:
```
The program BiliLite.exe version 1.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
```

### 操作步骤

```plain text
1. 电脑电源线松动导致意外关机并重启
2. 点击应用图标发生上述闪退问题
3. 在 Win11 设置中重置应用并卸载
4. 重启后重新安装最近的三个版本均发生同样的问题
```

### 期望结果

正常进入应用

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22621.2506)

### 设备类型

台式机

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
可能依赖挂了，试试卸载后使用脚本方式安装

**Comment by ChiotOnAGE** [comment]
> 可能依赖挂了，试试卸载后使用脚本方式安装

尝试过，但是无效。现在恢复正常了，但是中途来来回回干了很多事，不确定哪个才是关键：
1. 尝试恢复到上一个 system restore point 失败，想恢复到 restore 前的 restore point 继续失败（说实话 restore point 我几乎就没有一次用完不出岔子的）
2. 为了修复失败的 restore 导致部分 UWP 丢失，在 Powershell 5 用管理员权限运行了 `Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}` 以及 Windows Central 的 Thumbnail & Icon Cache Rebuilder, 重启后除了 WSL 和 BiliLite 外的 UWP 恢复, WSL 只能通过 `C:\Program Files\WSL\wsl.exe` 运行, `C:\Windows\System32\wsl.exe` 无法访问
3. 通过 `wsl --update --pre-release` 曲线救国恢复了各个 `wsl.exe` 的权限
4. 通过管理员权限运行 `dism /Online /Cleanup-Image /RestoreHealth` 并重启，BiliLite 正常工作。

很难相信，但是似乎最终解决问题的就是那个一般来说被认为没啥用的 `dism /RestoreHealth`.
