### ISSUE TITLE
切换到直播标签时一定会报错，偶尔还会直接闪退

### ISSUE THREAD

**Issue by thouser8** [ywmoyue/biliuwp-lite#404]
### Bug 描述

![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/d526e6a2-9ea1-4a1e-b091-ced4b199c73b)

### 操作步骤

```plain text
1.打开应用
2.出现报错
```

### 期望结果

修复报错

### 日志

2023-11-16 10:46:30.0863|ERROR|2|StackTrace.GetLiveHome|Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index|Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index    at System.Collections.Generic.List`1.get_Item(Int32) + 0x37
   at Newtonsoft.Json.Linq.JArray.get_Item(Object) + 0x51
   at BiliLite.Modules.LiveVM.<GetLiveHome>d__27.MoveNext() + 0x354

### 应用来源

Github/其他Github镜像站

### 安装方式

appx 直接安装

### 系统版本

Windows 11 23H2

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
请给出日志, 否则我们没有办法复现并修复潜在的bug.

**Comment by thouser8** [comment]
> 请给出日志，否则我们没有办法复现并修复潜在的 bug.

已上传

**Comment by GD-Slime** [comment]
> > 请给出日志，否则我们没有办法复现并修复潜在的 bug.
> 
> 已上传

确定是获取此url时报错了吗？如果不是的话请将日志里有"ERROR"的地方发出来或者将日志文件整个发出来。

**Comment by ywmoyue** [comment]
请填写这些 ![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/066d78b6-ac1e-4f3b-9533-a8119de8fd48)

**Comment by thouser8** [comment]
> > > 请给出日志，否则我们没有办法复现并修复潜在的 bug.
> > 
> > 
> > 已上传
> 
> 确定是获取此 url 时报错了吗？如果不是的话请将日志里有 "ERROR" 的地方发出来或者将日志文件整个发出来。

抱歉，现在改了

**Comment by thouser8** [comment]
> > > 请给出日志，否则我们没有办法复现并修复潜在的 bug.
> > 
> > 
> > 已上传
> 
> 确定是获取此 url 时报错了吗？如果不是的话请将日志里有 "ERROR" 的地方发出来或者将日志文件整个发出来。

抱歉，现在改了

**Comment by thouser8** [comment]
> 请填写这些 ![image](https://user-images.githubusercontent.com/28388300/283308311-066d78b6-ac1e-4f3b-9533-a8119de8fd48.png)

不好意思，现在已经填写

**Comment by ywmoyue** [comment]
@thouser8  卸载应用后用脚本安装了再试试

**Comment by thouser8** [comment]
> @thouser8 卸载应用后用脚本安装了再试试
> 
> 安装教程：https://github.com/ywmoyue/biliuwp-lite/blob/dev/document/install-readme.md

卸载了用脚本重装，问题依然存在
然后我发现这不是应用启动报错，而是切换到直播标签页才会报错
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/c3deb5d9-49f1-465d-8d16-bfa34b1ad3d7)
