### ISSUE TITLE
希望在视频详情页增加一个合集列表

### ISSUE THREAD

**Issue by thouser8** [ywmoyue/biliuwp-lite#415]
### 问题描述

我想要增加一个功能以便于观看合集，目前打开up主个人主页和视频详情页，都只能看到合集视频里的第一个视频，无法看到后续视频
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/cc3f5eb2-85c2-423a-ac30-a7499c4e9a4e)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/f03d4959-1246-40f3-a749-bef14f127dd4)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/a5255b56-4910-4266-81a9-ba02891eebb9)

### 描述解决方案

在视频详情页区域增加一个合集列表

### 附加信息

![a7125c9d80524955321bd4e2c2515519](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/d6b3ec84-0005-4177-aa22-6ab4ce78db2e)

### 代码贡献

否

**Comment by GD-Slime** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/5224a093-f5d6-4a4c-9e38-6744b0d8d9d2)
我这里是有播放列表的。请你检查是否还在用旧版本，或者可能是安装问题？

**Comment by thouser8** [comment]
> ![image](https://private-user-images.githubusercontent.com/82302542/286237840-5224a093-f5d6-4a4c-9e38-6744b0d8d9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzAyMDksIm5iZiI6MTcwMTI2OTkwOSwicGF0aCI6Ii84MjMwMjU0Mi8yODYyMzc4NDAtNTIyNGEwOTMtZjVkNi00YTRjLTllMzgtNjc0NGIwZDhkOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE0NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzRmMmE0NGI3OWNmZWM2MzYxZmEzMTcyYWViMzhmMTFmOTBiMmUxZDg2MDllMzQzZDdlYzYxZGU1N2U5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ux5oTkXZhCJk5SLyxSy8qlJzHtviXzeJmjbDknsR38Y) 我这里是有播放列表的。请你检查是否还在用旧版本，或者可能是安装问题？

重新确认了是用msix安装导致的问题，麻烦您了
