### ISSUE TITLE
二维码登录会导致视频合集的播放列表从详情页消失

### ISSUE THREAD

**Issue by thouser8** [ywmoyue/biliuwp-lite#419]
### Bug 描述

#415 
扫描二维码登录账号后，视频合集的播放列表会永久消失，就算退出登录也无法恢复。而使用验证码登录账号不会出现此问题
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/ed608833-b508-45a4-b29f-a1685c8b9736)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/1dabc73c-5da2-4308-9810-34a121d75450)

![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/7f0b966d-6977-442e-846a-078e855c4d0d)

### 操作步骤

```plain text
1.下载并打开应用，在未登录状态下可以正常看到列表
2.验证码登录账号，可以正常看到列表
3.二维码登录账号，视频详情页的列表选项卡消失
4.退出登录，列表选项卡仍然消失
```

### 期望结果

修复此问题，在二维码登录下仍然可以看到播放列表

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 11 23H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
应该是api有改动: https://app.bilibili.com/x/v2/view
正在测试
