### ISSUE TITLE
需求：希望能添加视频无损音质的支持

### ISSUE THREAD

**Issue by yzx23333** [ywmoyue/biliuwp-lite#43]
感谢大佬的接手维护。
如题，
请问是否可以添加对：https://www.bilibili.com/video/BV1zk4y147Tp
类似带有无损flac音频视频的支持？能添加一个类似网页版页面的无损开关来切换音质就好了。

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/de9a483f-c06d-479d-852a-83c8c6bed971)


在分辨率旁边加个酱紫的选择框？

**Comment by ywmoyue** [comment]
> 个人感觉没有必要列出低音质的选项吧？原acc的话尽可能高就好，b站acc不会超过320k的，但最高也有见过300k左右的样子。就像网页一样有一个亮起切换开关不可以吗？希望切换后的音轨参数能显示在现在的Audio Codec,DataRate中 对了，ci是坏掉了吗？没有看到pre-release呢😣

引入了高版本依赖注入库导致打的release包无法在win10上正常运行，正在测试具体情况

**Comment by ywmoyue** [comment]
> 我自行编译测试了一下，发现音质切换必须重载页面才能生效，不能即时切换； 以及这里的flac...可以统一成全大写吗😂 ![image](https://user-images.githubusercontent.com/69612876/248528414-701f860c-b7d6-477a-96b3-33357d38bacb.png) 希望大佬您能继续改进

感谢反馈，等下修了
以及这里的flac就是b返回的值
