### ISSUE TITLE
直播间弹幕延迟问题

### ISSUE THREAD

**Issue by RicardoDENG** [ywmoyue/biliuwp-lite#436]
### Bug 描述

观看半小时左右的直播后，弹幕开始有明显的延迟，表现出弹幕讨论内容与直播画面不同步，弹幕存在滞后的问题

### 操作步骤

```plain text
点开老e的直播，观看一定时长，弹幕开始有延迟，与手机端网页端弹幕不一致，点刷新又能重新同步
```

### 期望结果

弹幕与直播画面同步

### 截图

![(L7EVPKRC5(DI0O6%P{)MFY](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/66526387-51ac-4ea0-8920-93dcd46bb2e3)
![509F576E9E93B0F73AD981055AB29E53](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/2fae03b4-5f1c-4955-a95e-d0d6031d2cf1)
同一时间的uwp和手机端弹幕

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 10 20H2 (Build 19042)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
当uwp出现弹幕滞后时，其弹幕出现是否依旧是一批一批出现的？我在考虑是不是加的每条弹幕之间的延迟导致了此问题。 @RicardoDENG

**Comment by RicardoDENG** [comment]
依旧是一批一批地出，只是延后了
