### ISSUE TITLE
打开动态的"互动抽奖"按钮后显示需要重新登录

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#442]
### Bug 描述

![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/edab5af1-269d-42e8-aa9f-002aa9b79c5c)
使用二维码登录。

### 操作步骤

```plain text
1. 打开某有互动抽奖的up的动态
2. 点击"互动抽奖"按钮
3. 等待加载后，提示需要重新登录。
```

### 期望结果

正常显示抽奖内容

### 日志

日志无异常

### 已定位描述

![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/55019eef-cbc2-41a4-a96a-d84b7d4f6a28)
此处`OpenLottery`是否需要传递cookie进去？这个问题看起来像是cookie没有被正确的传递到此webview导致的。
有点超出能力范围，还请会的大佬修理。

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
改webview2改漏了 https://github.com/ywmoyue/biliuwp-lite/commit/bcad3990efd3bd37a1ec48ec3cf3e6ad9c5e2def

**Comment by GD-Slime** [comment]
> 改webview2改漏了 [bcad399](https://github.com/ywmoyue/biliuwp-lite/commit/bcad3990efd3bd37a1ec48ec3cf3e6ad9c5e2def)

目前我看到其他的例如投票是直接打开一个新页面的，这个互动抽奖是否可以还是基于原来的dialog呢？这样我感觉会更美观。

**Comment by ywmoyue** [comment]
> 目前我看到其他的例如投票是直接打开一个新页面的，这个互动抽奖是否可以还是基于原来的dialog呢？这样我感觉会更美观。

这里操作逻辑我应该不会动，可以麻烦找一个动态有抽奖的up吗，我动态翻半天没找到
