### ISSUE TITLE
个人页视频的最多收藏按钮需要移除

### ISSUE THREAD

**Issue by ichigomikako** [ywmoyue/biliuwp-lite#443]
### Bug 描述

up主个人页面最新发布和最多收藏数据内容相同，都是最新发布的数据

### 操作步骤

```plain text
1.点进一个up主页
2.切换列表为最多收藏，内容和最新发布重复
```

### 期望结果

可以按照最多收藏排序

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.9

个人页视频在4.6.9之后切换为app的grpc实现，不再支持最多收藏排序
