### ISSUE TITLE
直播二级分区导致闪退

### ISSUE THREAD

**Issue by Yin-Kong** [ywmoyue/biliuwp-lite#446]
### Bug 描述

进入直播板块，如果进”娱乐“分支，会导致闪退（其他分支会正常显示二级分区，如生活分支分支能显示户外直播二级分区）

### 操作步骤

```plain text
1.打开应用
2.进入直播板块
3.点击全部标签
4.上侧选项栏选择娱乐
```

### 期望结果

显示子分支

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

台式机

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
请上传一下日志文件，有助于bug修复。
理论上，目前直播板块由于b站api更换，并不会有`全部标签`这个按钮。请问你在使用什么登录方式，什么版本，什么平台呢？
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/c35ab901-6860-468c-bf00-2a2d1df8b4ee)

**Comment by Yin-Kong** [comment]
日志已上传，登录方式为之前扫码登录（现在打开会报错无法获取cookies，但能正常访问个人主页，使用版本为4.6.23.0，平台为X64台式机）![Uploading image.png…]()
[20231220.log](https://github.com/ywmoyue/biliuwp-lite/files/13724231/20231220.log)

**Comment by GD-Slime** [comment]
@Yin-Kong 非常奇怪！在前几个版本已经将`mobi_app`这个请求api的参数从`android` 更换到了`iphone`, 然而你的日志里还是全部是`mobi_app=android`. 
请退出重新登录试试，如果还是不行的话请卸载重新从脚本安装。检查是否还有`mobi_app=android`的请求。

**Comment by Yin-Kong** [comment]
重新登陆日志已变成ios，且对应板块消失，对应问题解决

**Comment by ywmoyue** [comment]
> @Yin-Kong 非常奇怪！在前几个版本已经将`mobi_app`这个请求api的参数从`android` 更换到了`iphone`, 然而你的日志里还是全部是`mobi_app=android`. 请退出重新登录试试，如果还是不行的话请卸载重新从脚本安装。检查是否还有`mobi_app=android`的请求。

@GD-Slime  这个我改的，为了避免之前的用户登录全部失效，仅二维码新登录的用户才使用ios的app key  https://github.com/ywmoyue/biliuwp-lite/commit/e592833a80948dca3cb9fff9713234122c8ba131

也就是说，使用密码登录仍然会有这个问题
