### ISSUE TITLE
首页推荐的番剧打开会报错

### ISSUE THREAD

**Issue by wuyuehuasuki** [ywmoyue/biliuwp-lite#452]
### Bug 描述

打开部分番剧会报错
首页 - 推荐  ：带有番剧标签的打开会报错
首页 - 番剧  ：我的追番/今日更新/番剧推荐/热门番剧/泡面番  以上正常可播放  
出错X ：精彩推荐/咨询档/周末剧场/

### 操作步骤

```plain text
1.打开应用
2.点击首页推荐的番剧
3.出现未处理的错误
```

### 期望结果

最近出现的问题，从4.6.19升级到4.6.23未解决。

### 截图

![C M)D)B1J8OXHC7 M~0 @WE](https://github.com/ywmoyue/biliuwp-lite/assets/115102770/7a1b8d63-4977-494a-a913-e08a8f21e0e4)
![`CD46 F~HDW6DUIQ VAT1{K](https://github.com/ywmoyue/biliuwp-lite/assets/115102770/e402bc06-04b2-4569-a090-ff8326f6e8dd)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 10 1903 (Build 18362)

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
你好，能否发一下日志？这很有利于bug修复。

**Comment by wuyuehuasuki** [comment]
> 你好，能否发一下日志？这很有利于bug修复。
[20231223.log](https://github.com/ywmoyue/biliuwp-lite/files/13759359/20231223.log)
附带一个视频下载没有速度，也无法删除的问题。
[20231223下载视频出错.log](https://github.com/ywmoyue/biliuwp-lite/files/13759360/20231223.log)

**Comment by GD-Slime** [comment]
应该是`https://bangumi.bilibili.com/view/web_api/season?season_id=`这个api不能用了. 我这里复现显示返回502

**Comment by GD-Slime** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/918 `https://api.bilibili.com/pgc/web/season/section`现在对于港澳台的番剧也无法返回信息了

**Comment by GD-Slime** [comment]
@ywmoyue 我测试首页打开番剧仍然会有错误，请重新打开一下吧
