### ISSUE TITLE
二维码登录后热门页中的视频没有up主名称

### ISSUE THREAD

**Issue by forchannot** [ywmoyue/biliuwp-lite#476]
### 问题描述

在热门页中添加up主的名称，目前的长这样，看不到是哪个up发的视频
![image](https://github.com/ywmoyue/biliuwp-lite/assets/100580891/18b80da3-cbf6-4316-aaa2-11023bd057c0)

### 描述解决方案

将排版改成类似下面这样的
![image](https://github.com/ywmoyue/biliuwp-lite/assets/100580891/3c1dc359-bac7-41e9-8cec-9454dedb2eb4)

### 代码贡献

否

**Comment by ywmoyue** [comment]
是使用二维码登录导致的bug，使用验证码登录或者不登录的话up主名称是有的
