### ISSUE TITLE
互动视频功能代码生命周期问题

### ISSUE THREAD

**Issue by Liuyiyang888888** [ywmoyue/biliuwp-lite#492]
### 问题描述

我想要使用互动视频的互动功能(指选项按钮)，以便于看互动视频

### 描述解决方案

在互动视频里添加选择按钮

### 代码贡献

否

**Comment by GD-Slime** [comment]
Duplicate of #368
过几天看一下

**Comment by ywmoyue** [comment]
@Liuyiyang888888 问下是哪个互动视频没有选项按钮，我这边测的是有的
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/32a68f66-e67e-4b48-a42e-b99372864e3c)

**Comment by Liuyiyang888888** [comment]
我再看看

**Comment by Liuyiyang888888** [comment]
等我一下

**Comment by Liuyiyang888888** [comment]
我明天看，等我一下啊

**Comment by Liuyiyang888888** [comment]
不行
![image](https://github.com/ywmoyue/biliuwp-lite/assets/146803556/5ff7fafc-8dc7-4a13-a2c8-6d23c427a52d)

**Comment by ywmoyue** [comment]
@Liuyiyang888888 你换成用短信验证码登录后再试试，可能是二维码登录导致的

**Comment by Liuyiyang888888** [comment]
ok

**Comment by Liuyiyang888888** [comment]
还有其他人维护的v4

**Comment by Liuyiyang888888** [comment]
不行啊

**Comment by Liuyiyang888888** [comment]
[好像这个（点击查看）](https://github.com/ywmoyue/biliuwp-lite/issues/368)

**Comment by ywmoyue** [comment]
在修复了，这块代码生命周期有问题

**Comment by Liuyiyang888888** [comment]
万分感谢！

**Comment by Liuyiyang888888** [comment]
OK了

**Comment by Liuyiyang888888** [comment]
互动视频第一个选项是对的，第二次选择变成了第一次选项的按钮，点击会回到第二次选项前

**Comment by Liuyiyang888888** [comment]
还没OK

**Comment by Liuyiyang888888** [comment]
看见了吗

**Comment by Liuyiyang888888** [comment]
谢谢

**Comment by Liuyiyang888888** [comment]
好了吗

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.25.7

**Comment by Liuyiyang888888** [comment]
好了，万分感谢！
