### ISSUE TITLE
regression: 重构http请求后登录挂了

### ISSUE THREAD

**Issue by MoetaYuko** [ywmoyue/biliuwp-lite#5]
https://github.com/ywmoyue/biliuwp-lite/commit/4f6f6b584ddf520e9c91c8ec32535afaae8388a9 之后扫码登录并在手机上确认后会弹出提示“账号未登录”，并且事实上也确实没有登录

**Comment by ywmoyue** [comment]
我处理重定向响应和错误响应的顺序搞错了，https://github.com/ywmoyue/biliuwp-lite/commit/e8aac765c2da356e6076045d201a9e28f043bc5b 已修复
