### ISSUE TITLE
同时实现方向键快进/长按三倍速

### ISSUE THREAD

**Issue by CKopoer** [ywmoyue/biliuwp-lite#511]
### 问题描述

目前方向键快进和控制倍速只能2选1，能否实现类似官方客户端，点按→快进，长按三倍速

### 描述解决方案

区分点按、长按→键

### 代码贡献

否

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/03e2cc6b-d4d7-4838-9981-052e3f5390ab)

@CKopoer 这样设置是否符合你的需求
