### ISSUE TITLE
播放视频一段时间后卡死后闪退

### ISSUE THREAD

**Issue by minortex** [ywmoyue/biliuwp-lite#512]
### Bug 描述

无论全屏或者不是全屏，播放视频一段时间后卡死后闪退。尝试重启电脑，重装应用和将g-sync和垂直同步关闭都不起作用。

### 操作步骤

```plain text
1. 打开应用
2. 随便选一个视频，播放
3. 一段时间后声音消失，画面冻结，几秒钟后应用闪退
```

### 期望结果

正常播放视频

### 日志

日志未出现明显问题

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 22H2 (Build 22621.2506)

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
什么显卡

**Comment by minortex** [comment]
> 什么显卡

4060 8g laptop，开启独显直连

**Comment by minortex** [comment]
我切换了一下optimus和直连模式，发现貌似不闪退了？没法复现，先关掉吧，抱歉

**Comment by minortex** [comment]
补充一下，在win设置的gpu里面把哔哩哔哩设置成核显就不会闪退了，用nvidia控制面板没有用
