### ISSUE TITLE
扫二维码登录后只有部分权限，不显示头像，点击动态、关注、个人中心，以及点击视频up名字，均无法正常进入。

### ISSUE THREAD

**Issue by cdc1150** [ywmoyue/biliuwp-lite#515]
### Bug 描述

扫二维码登录后，首页右上角头像位置为空白。左键单击头像所在空白处，能出现下拉菜单，用户信息显示异常。
如图1.
![BL-issue-shot-01](https://github.com/ywmoyue/biliuwp-lite/assets/150724687/c8f6000b-a686-4d19-ad89-22080fde20b0)

左键单击“个人中心”无法进入，窗口下方提示“出现一个未知错误，已记录”。但“我的消息”可正常进入页面，且显示头像。如图2.

![图像_2024-03-04_230002269](https://github.com/ywmoyue/biliuwp-lite/assets/150724687/ab7a82e2-1ba3-4830-ad1d-8713f64c6950)

在窗口左上方，左键单击“动态”也无法进入，窗口下方提示“出现一个未知错误，已记录”。如图3.

![图像_2024-03-04_225108200](https://github.com/ywmoyue/biliuwp-lite/assets/150724687/0e3f587d-87aa-4562-9f9e-8bbdcc53db31)

在视频播放界面，左键单击视频up主名字，无法进入其页面，窗口下方提示“出现一个未知错误，已记录”。如图4.

![BL-issue-shot-03](https://github.com/ywmoyue/biliuwp-lite/assets/150724687/65f13d9a-c3b3-45af-8893-f2625d2762c5)

账号为手机号注册，是lv2级正式会员，在网页、Android客户端、Windows客户端可正常登录使用。
所用系统为：Windows 10 专业版 22H2(19045.4046)
uwp安装方式为：github下载x64.zip解压后使用powershell安装。

不知是否与账号未提交身份证实人验证有关。

### 操作步骤

```plain text
打开uwp
点击右上角头像符号
切换至二维码登录
手机客户端扫码
登录后问题即出现。

且重启uwp、退出账号重新登录、重启Windows等各种方式，均100%复现。
```

### 期望结果

扫描二维码登录后，可以点击“动态”查看关注对象的更新情况，可以点击up主名字进入相关页面。

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
使用短信验证码登录是否正常

**Comment by ywmoyue** [comment]
应该与账号等级和实名认证无关，我测了lv2的小号二维码登录后是正常的，需要你这边发下日志我看一下，注意发日志前检查日志中有无敏感内容

日志文件在帮助页最下方能找到位置

**Comment by cdc1150** [comment]
> 应该与账号等级和实名认证无关，我测了lv2的小号二维码登录后是正常的，需要你这边发下日志我看一下，注意发日志前检查日志中有无敏感内容
> 
> 日志文件在帮助页最下方能找到位置

好的，麻烦请看一下。
[20240304.log](https://github.com/ywmoyue/biliuwp-lite/files/14506823/20240304.log)

**Comment by GD-Slime** [comment]
@ywmoyue 看了下日志，可能是现在新注册的用户uid超过int32最大值导致的错误

**Comment by cdc1150** [comment]
> @ywmoyue 看了下日志，可能是现在新注册的用户uid超过int32最大值导致的错误

太给力了，期待下一个版本！没想到是uid的问题，之前几个月不断重装、换版本什么的都没有想到解决办法。

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.26.2

@cdc1150 麻烦验证一下

**Comment by cdc1150** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.26.2
> 
> @cdc1150 麻烦验证一下

非常感谢！原描述的问题已经全部验证解决了。退出重新登录也一切正常。
