### ISSUE TITLE
希望增加简介链接可视且直接由浏览器打开。

### ISSUE THREAD

**Issue by TobyLi223** [ywmoyue/biliuwp-lite#519]
### 问题描述

目前内置浏览器反应很慢，且极其不稳定

### 描述解决方案

如标题

### 代码贡献

否

**Comment by ywmoyue** [comment]
能否详细描述下

**Comment by TobyLi223** [comment]
![屏幕截图 2024-03-11 230033](https://github.com/ywmoyue/biliuwp-lite/assets/96031501/060ea75a-78dc-4bb4-9325-afeb3a556f38)
不需要特别标注，青色的“网页链接”，点击后会在app里打开，会很卡。而且网页链接这四个字让我无法直接观察这些链接的域名，也无法直接复制。之前我都是把视频链接分享出去在浏览器打开，很麻烦。

**Comment by TPAXcc** [comment]
建议
增加 悬停在 网页链接 弹出预览框
增加 左Ctrl+单击 浏览器打开
增加 右键菜单复制

**Comment by TPAXcc** [comment]
> 建议 增加 悬停在 网页链接 弹出预览框 增加 左Ctrl+单击 浏览器打开 增加 右键菜单复制

可以参考 Windows终端 对URL的处理方式

**Comment by TPAXcc** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/5865ce04-561d-48ad-a0c2-e32537f49551)
like this

**Comment by ywmoyue** [comment]
> @TPAXcc 试试打开 APP 内的设置 -> 个性化 -> 使用浏览器打开无法处理的链接。或许是你想要的功能？

@TPAXcc @TobyLi223  由于视频简介是富文本转换出来得到的，可以加个tooltip显示链接，但是加其他操作就比较困难了，可以使用楼上的设置项直接用浏览器打开链接
