### ISSUE TITLE
弹幕发送不了

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#521]
### Bug 描述

如题，发送弹幕时显示程序出现错误
![image](https://github.com/ywmoyue/biliuwp-lite/assets/124747209/4d8d1a33-25d3-4f01-beb0-f6db635236f7)

### 操作步骤

```plain text
打开视频，输入弹幕，点击发送，弹窗失败
```

### 期望结果

弹幕发送成功

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x86

### 应用架构

x86

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
看了下这个问题，弹幕实际上发送出去了，这个错误是因为没有对寒霜弹幕使做好兼容导致的，下个版本修复
