### ISSUE TITLE
首页推荐页面进入直播间显示视频加载失败

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#533]
### Bug 描述

如题，在直播界面进入时可正常观看，但是在推荐点击十显示视频加载失败

### 操作步骤

```plain text
打开应用
进入推荐页面
点击直播
视频加载失败
```

### 期望结果

正常进入直播间观看

### 截图

![image](https://github.com/ywmoyue/biliuwp-lite/assets/124747209/ade12312-5ae6-4158-a89f-dd8122b0bcde)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x86

### 应用架构

x86

### 代码贡献

我更擅长发现问题

**Comment by Shaddoll126** [comment]
更新4.6.28.0后依旧存在相同bug

**Comment by ywmoyue** [comment]
> 更新4.6.28.0后依旧存在相同bug

这个问题还没处理，处理的issue我会给打对应的标签和里程碑

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.28.2 @Shaddoll126 麻烦验证一下

**Comment by Shaddoll126** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.28.2 @Shaddoll126 麻烦验证一下

已经下载临时版本了  现在可以首页推荐直接进入直播间了
