### ISSUE TITLE
评论下显示热门回复

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#542]

**Comment by ywmoyue** [comment]
@lyppiao 麻烦测一下 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.28.1

**Comment by lyppiao** [comment]
> @lyppiao 麻烦测一下 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.28.1

可以用，主要问题有两个。
1.回复的字体太小了，看着很吃力，需要加大。
2.短回复显示效果还行，长回复用户id底下空着那么大一块空间，看着很难受。希望可以直接显示到最左边，把那些空间利用上。
![屏幕截图 2024-03-27 001937](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/f1421377-0cd4-40b9-8ba7-d9f6f1a0616a)
![屏幕截图 2024-03-27 002200](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/136f5848-774d-45c9-a0ed-2f7ca2040fe9)

**Comment by lyppiao** [comment]
如果有做显示左边的话，能不能顺便把主评论，和热门回复的灰框，都直接一起拉过去。这东西应该是同一个代码吧。
也就是把头像底下的空白处，也用来显示内容。示意图如下
这样每一行都能显示更多的文字，用更少的空间，显示更多的内容。
![屏幕截图 2024-03-27 011239](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/58c86421-fe00-439d-beae-1cc3c324b706)

**Comment by lyppiao** [comment]
id变色和up标志？这玩意无所谓，有的话好看一点，没有的话也完全不影响使用。
![屏幕截图 2024-03-27 013757](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/4d757cb9-a7cf-46e0-8bbc-40f47a5a433f)

**Comment by lyppiao** [comment]
官方评论区画幅更大，每行可以显示更多的字，我们这边的评论区就很细长。
我在想 做热门回复左置 的代码，能不能套用到主评论区上。增加一个开关，利用头像下的空间，在不改变画幅的前提下，显示更多内容。
![屏幕截图 2024-03-27 014949](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/5882cf89-c71b-4199-bddf-eda27a5b4c79)
![屏幕截图 2024-03-27 011239](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/2a89b091-89a3-44a2-934d-20301c42d88b)

**Comment by ywmoyue** [comment]
@lyppiao 可以在设置个性化中修改右侧视频详情宽度为299看看效果，我感觉怪怪的

**Comment by lyppiao** [comment]
299还行，显示的内容多了，主评论320一行16字 变 299一行19字。这个数有什么讲究吗？感觉更大更小的字数都更少，除非拉到非常大。
感觉怪怪的应该是左右白边不对称，左边很小，右边很大。因为右边还有那个拖动标的空间，拖动时那个标会很粗，看起来就正常了。但是没拖时的细标，甚至标都不在那里的时候，看起来就很奇怪。
![屏幕截图 2024-03-27 144259](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/6de5547c-2707-4e9f-b785-d5be6319fcc5)

**Comment by lyppiao** [comment]
299还行，显示的内容多了，主评论320一行16字 变 299一行19字。这个数有什么讲究吗？感觉更大更小的字数都更少，除非拉到非常大。
感觉怪怪的应该是左右白边不对称，左边很小，右边很大。因为右边还有那个拖动标的空间，拖动时那个标会很粗，看起来就正常了。但是没拖时的细标，甚至标都不在那里的时候，看起来就很奇怪。
![屏幕截图 2024-03-27 144259](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/d5a520b9-3980-484d-86ad-97ff045cd5eb)
![屏幕截图 2024-03-27 145146](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/090aa108-694a-4dcd-942b-e35c88f2311f)

**Comment by ywmoyue** [comment]
@lyppiao 299宽度没啥特别的意义，之前随便设的宽度小于300评论控件进入狭窄模式内容跨列

https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.28.2 这个版本调整了下样式并将这个宽度触发值设置为360，麻烦再测一下

**Comment by lyppiao** [comment]
基本比较完善了。就是文字完全贴边，跟灰框连在一起，看着难受。
能不能把灰框两边向外扩，或者文字向内缩，留出一个小边缘，大概就是最底下狗头旁边的大小。
![屏幕截图 2024-03-27 231951](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/4e5396a1-e7ea-4023-bdd3-c708fbd21356)

**Comment by lyppiao** [comment]
基本比较完善了。就是文字完全贴边，跟灰框连在一起，看着难受。
能不能把灰框两边向外扩，或者文字向内缩，留出一个小边缘，大概就是底下狗头旁边的大小。
![屏幕截图 2024-03-27 231951](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/fab0f819-a2bd-49e9-a962-bf7048a66e03)

感觉右边是自适应的，贴边的情况比较少，左边是全部都贴边顶着的。
![屏幕截图 2024-03-27 232935](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/8295cb0a-087d-4b95-a32b-dc1770394335)

**Comment by lyppiao** [comment]
发现一个奇怪的bug，部分回复在外面不显示，只有一个空位。
发现视频BV1Et421V7mv
![屏幕截图 2024-03-28 004334](https://github.com/ywmoyue/biliuwp-lite/assets/143381863/5e127d53-a5b2-450e-bf9f-e4d0fb9b58b2)
