### ISSUE TITLE
使用 Clash for Windows 代理时，打开首页加载不出来

### ISSUE THREAD

**Issue by leskytian** [ywmoyue/biliuwp-lite#55]
已经在 UWP Loopback 里排除了。并且用的是规则模式（规则来自 [https://github.com/Loyalsoldier/clash-rules](https://github.com/Loyalsoldier/clash-rules)），实测访问哔站网页是直连。

**Comment by ywmoyue** [comment]
非代码问题在这里讨论https://github.com/ywmoyue/biliuwp-lite/discussions/54
