### ISSUE TITLE
分P实现优化

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#550]
### 问题描述

无法显示完整过长的分P标题

### 描述解决方案

根据标题长度判断需要几行显示并调整字体px数
![image](https://github.com/ywmoyue/biliuwp-lite/assets/91980905/b3334742-1e8b-4563-909c-505c160f16b0)

### 附加信息
关联 #83

### 代码贡献

否

**Comment by GD-Slime** [comment]
这里做个单行循环滚动显示文字是否有更美观的效果？
~但是稍微查了一下xaml做这个好像很麻烦...~

**Comment by pheotry** [comment]
> 这里做个单行循环滚动显示文字是否有更美观的效果？ ~但是稍微查了一下xaml做这个好像很麻烦...~

过长的直接换行得了，滚动显示看似美观，实际上用起来并不是很方便

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 麻烦测一下

**Comment by ywmoyue** [comment]
没有回复，我这边就先发版本了，有问题下个版本再处理

**Comment by TPAXcc** [comment]
> 没有回复，我这边就先发版本了，有问题下个版本再处理

报意思，才看到
经测试未发现bug
