### ISSUE TITLE
建议默认启用 新窗口打开图片预览

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#552]
### Bug 描述

.

### 操作步骤

```plain text
.
```

### 期望结果

.

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by TPAXcc** [comment]
开错成 BUG report 了不好意思

**Comment by ProJend** [comment]
为什么，和#272有关？

**Comment by ywmoyue** [comment]
#272 问题已处理，已不需要默认启用新窗口打开图片预览
