### ISSUE TITLE
页面中输入框无法输入空格

### ISSUE THREAD

**Issue by slinar** [ywmoyue/biliuwp-lite#555]
### Bug 描述

直播界面右下角聊天输入框无法输入空格

### 操作步骤

```plain text
打开任何直播间,右下角可以输入文字但是无法输入空格
```

### 期望结果

可以输入空格

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 10 21H1 (Build 19043)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by AnyoeDove** [comment]
版本4.6.28.2 事实上所有输入框内输入空格都不显示
