### ISSUE TITLE
深色模式下启动图背景改为黑色，白色有点刺眼

### ISSUE THREAD

**Issue by pheotry** [ywmoyue/biliuwp-lite#558]
### 问题描述

如上

### 描述解决方案

添加深色模式启动图

### 代码贡献

否

**Comment by ywmoyue** [comment]
@pheotry  启动页背景做不到跟随应用的主题变化，但是我这边可以改成透明背景后跟随系统的主题变化，因为原本不是纯白色，所以这个更改可能会导致浅色系统主题的应用启动页更加刺眼
下个版本出一下试试
