### ISSUE TITLE
个人主页动态修复后出现的相关bug

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#562]
### Bug 描述

1. 纯文字类/文字图片混合类动态无法显示文字 -> 例子: https://space.bilibili.com/4255540/dynamic
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/f4157ebd-087e-4aea-9a01-db2fa64f863c)

3. 专栏动态无法显示相关内容 -> 例子: https://space.bilibili.com/178047796/dynamic
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/dd02a6b6-4507-4e5f-b927-7f7b074cff61)

5. 某些动态图片未做相关长宽处理
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/8f6f1194-1c3b-42d2-9ba9-60c8ee0f4315)

7. 动态评论区以视频评论区形式调出
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/e9bd75a6-a1ac-42c1-8f73-d216c5728570)

### 操作步骤

```plain text
打开相关例子即可复现
```

### 期望结果

正常显示

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
第一点和第二点我这边看着没问题，我猜可能又是登录方式不一致导致数据结构不一样，我再处理一下
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/40941df3-1e7d-42c9-b959-b280f02668c5)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/26c43c70-50f6-4118-989e-84b655800815)


第四点故意不用原来的ContentDialog来显示评论的，目的是能以ContentDialog来显示评论中的图片

**Comment by GD-Slime** [comment]
我也怀疑是登录方式的问题，所以又重新二维码登录了一下，但是还是有此故障。

**Comment by ywmoyue** [comment]
我本来是验证码登录的，我重新二维码登录后复现了，我处理下
