### ISSUE TITLE
动态界面出现鉴权失败，重新登陆后恢复正常但一段时间后又出现鉴权失败

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#574]
### Bug 描述

如题，尝试过二维码登录与短信验证码登录，均会在一段时间后出现鉴权失败（大约半小时

### 操作步骤

```plain text
打开应用，选择动态，弹出鉴权失败
```

### 期望结果

正常出现动态界面

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
记录涉及接口 [GET]https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new
