### ISSUE TITLE
部分番剧无法播放

### ISSUE THREAD

**Issue by pheotry** [ywmoyue/biliuwp-lite#584]
### Bug 描述

凡人修仙传无法播放，但是看了下其他番剧又能正常播放。

### 操作步骤

```plain text
从历史记录里播放 或者 直接搜索播放 都不行
```

### 期望结果

正常播放

### 截图

![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/ac0bc8ad-a95b-45b9-8ea9-6b95f1e24220)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

win11 22635.3430

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
```
<LoadSeasonDetail>d__95.LoadSeasonDetail|JSON integer 2173634096 is too large or small for an Int32. Path 'data.stat.views', line 1, position 977109.
at BiliLite.ViewModels.Season.SeasonDetailPageViewModel.LoadSeasonDetail(String seasonId)
```
@ywmoyue int越界问题

**Comment by ywmoyue** [comment]
> ```
> <LoadSeasonDetail>d__95.LoadSeasonDetail|JSON integer 2173634096 is too large or small for an Int32. Path 'data.stat.views', line 1, position 977109.
> at BiliLite.ViewModels.Season.SeasonDetailPageViewModel.LoadSeasonDetail(String seasonId)
> ```
> @ywmoyue int越界问题

好的，非常感谢帮忙
