### ISSUE TITLE
播放高画质视频会停止播放卡在缓冲

### ISSUE THREAD

**Issue by JiayanJohnnyChu** [ywmoyue/biliuwp-lite#587]
### Discussed in https://github.com/ywmoyue/biliuwp-lite/discussions/579

<div type='discussions-op-text'>

<sup>Originally posted by **JiayanJohnnyChu** April 13, 2024</sup>
### Bug 描述

播放高画质视频（如4K或杜比视界）时，在播放数分钟后会停止播放并显示缓冲中，但会一直保持在这个状态无法继续播放，且此时通过任务管理器发现并没有实际的数据传输。（网络没有问题，任务管理器显示正常缓冲速度可达500mbps以上）
同时对于高画质视频，跳转到数分钟以后的位置也会一直显示缓冲中，任务管理器显示会有一个数百mbps的传输，其后便不再有网络活动。

### 操作步骤

```plain text
1. 打开应用并打开高画质视频（如 https://b23.tv/BV1Vx4y1a7VB）。
2. 全屏播放该视频。
3. 数分钟后停止播放，并显示缓冲中。
4. 等待一段时间仍无法继续播放，暂停后再次播放也无法继续。
```

### 期望结果

正常播放高画质视频并能正常进行跳转

### 日志

[Untitled.txt](https://github.com/ywmoyue/biliuwp-lite/files/14967199/Untitled.txt)

### 应用来源

Github/其他Github镜像站

### 系统版本

Windows 11 23H2

### 设备类型

平板

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题</div>

**Comment by ywmoyue** [comment]
目前没有什么好办法解决这个问题，我复现后也没看到播放器库有输出什么奇怪的日志
但是下载下来后播放似乎是没问题的

本来想着重构播放器方便后续问题定位和更换别的播放器库的，但是一直没时间搞

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.4 试试4.7.4设置播放器类型为FFmpegInterop
