### ISSUE TITLE
改进新动态评论页面

### ISSUE THREAD

**Issue by forchannot** [ywmoyue/biliuwp-lite#588]
### Bug 描述

现在新动态页面点击评论区后会在顶部出现加载，并且评论出来后无法翻页（例如滚轮）

### 操作步骤

```plain text
打开最新版动态评论区
```

### 期望结果

希望能恢复到原来的评论加载模式，修复评论翻页，用户空间的动态界面就比较符合预期
![image](https://github.com/ywmoyue/biliuwp-lite/assets/100580891/a4066e68-3216-4c4e-a674-f5c4cc3b0ef1)

### 截图

![recording](https://github.com/ywmoyue/biliuwp-lite/assets/100580891/827e4a1d-b4e7-4547-a975-5045cc943441)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这是个bug，我会基于现在这个方式进行修复，但不会改回原来的方式，因为原来的评论显示方式会导致打开评论区图片时图片出现在评论区底下被评论区盖住
