### ISSUE TITLE
新版本动态页面宽度错误

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#590]
### Bug 描述

测试版本4.6.29.4，动态页面选择瀑布流排列后，页面顶部tab未同时拓宽。
![image](https://github.com/ywmoyue/biliuwp-lite/assets/124747209/b8a8d180-efa6-41c4-90df-7f40c2eb1640)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/124747209/4de499ea-6953-4fa3-8956-38b0aafe68f6)

### 操作步骤

```plain text
打开应用，进入动态页面，选择瀑布流排列，顶部tab未拓宽
```

### 期望结果

和旧版本一样tab变宽

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
没感觉这个变宽有什么意义，不过加上也行

**Comment by Shaddoll126** [comment]
> 没感觉这个变宽有什么意义，不过加上也行

hh  主要是之前版本的瀑布流状态下tab栏是靠左的  居中后确实会有不习惯
