### ISSUE TITLE
二维码登录时部分动态导致应用崩溃

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#608]

**Comment by ywmoyue** [comment]
@SuanOrange 麻烦测一下这个版本是否还会崩溃 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.1

**Comment by SuanOrange** [comment]
更新版本后，没有出现崩溃

**Comment by SuanOrange** [comment]
更新版本后，暂时没有出现崩溃

**Comment by GD-Slime** [comment]
@ywmoyue 我这里更新版本后出现崩溃了... 
```
2024-05-03 10:07:56.2117|ERROR|3|DynamicParseExtensions.UserDynamicStringToRichText|用户动态文本转富文本失败|无法找到与此错误代码关联的文本。

wfc: no '<' in attribute value [Line: 5 Position: 256]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at BiliLite.Extensions.DynamicParseExtensions.UserDynamicStringToRichText(String txt, String id, List`1 emote, JObject extend_json, List`1 wordNodes, String title, String bindingCommands)
```

**Comment by GD-Slime** [comment]
目前发现一个稳定产生故障的地方，还是这位用户： 
![image](https://github.com/ywmoyue/biliuwp-lite/assets/82302542/dc78f168-6692-45e5-9ddd-49fa2e7375ba)
点击按钮后就会卡住并崩溃
```
2024-05-03 10:18:14.6376|ERROR|3|StringExtensions.ToRichTextBlock|富文本转换失败: 页面还在，你粘贴的时候要去除B站尾缀https://pan.baidu.com/s/1stfbVk0Au9M2OB-ILg5cnA...|无法找到与此错误代码关联的文本。

wfc: no '<' in attribute value [Line: 4 Position: 339]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at BiliLite.Extensions.StringExtensions.ToRichTextBlock(String txt, JObject emote, Boolean isLive, String fontColor, String fontWeight, String lowProfilePrefix)
```

**Comment by ywmoyue** [comment]
> 目前发现一个稳定产生故障的地方，还是这位用户： ![image](https://private-user-images.githubusercontent.com/82302542/327631847-dc78f168-6692-45e5-9ddd-49fa2e7375ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDQ4MjQsIm5iZiI6MTcxNDcwNDUyNCwicGF0aCI6Ii84MjMwMjU0Mi8zMjc2MzE4NDctZGM3OGYxNjgtNjY5Mi00NWU1LTlkZGQtNDlmYTJlNzM3NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDAyNDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjYyY2VmZDc4MWNhOWRhZDE2NjIwYTg0M2VjNjk5ODA4ZjRmMTQyNzgyNGExMGZkOGE5MDRiYjg2ZDQwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bQuswBIqXhPmz66dgsmOgl4u4LPZa3aFN-0tPSqkBfU) 点击按钮后就会卡住并崩溃
> 
> ```
> 2024-05-03 10:18:14.6376|ERROR|3|StringExtensions.ToRichTextBlock|富文本转换失败: 页面还在，你粘贴的时候要去除B站尾缀https://pan.baidu.com/s/1stfbVk0Au9M2OB-ILg5cnA...|无法找到与此错误代码关联的文本。
> 
> wfc: no '<' in attribute value [Line: 4 Position: 339]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
>    at BiliLite.Extensions.StringExtensions.ToRichTextBlock(String txt, JObject emote, Boolean isLive, String fontColor, String fontWeight, String lowProfilePrefix)
> ```

这个是评论区转换富文本崩溃了，和动态调用的不是同一个方法，看来对于链接需要做一样的处理

**Comment by ywmoyue** [comment]
> @ywmoyue 我这里更新版本后出现崩溃了...
> 
> ```
> 2024-05-03 10:07:56.2117|ERROR|3|DynamicParseExtensions.UserDynamicStringToRichText|用户动态文本转富文本失败|无法找到与此错误代码关联的文本。
> 
> wfc: no '<' in attribute value [Line: 5 Position: 256]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
>    at BiliLite.Extensions.DynamicParseExtensions.UserDynamicStringToRichText(String txt, String id, List`1 emote, JObject extend_json, List`1 wordNodes, String title, String bindingCommands)
> ```

这个日志打印得有问题，定位不出哪条动态，转换的xaml文本是怎样的，我改改然后跑个包再试试
