### ISSUE TITLE
弹幕字体显示异常

### ISSUE THREAD

**Issue by thouser8** [ywmoyue/biliuwp-lite#609]
### Bug 描述

![423fbbc8ef59a1e7cecaf63a4f1ee5b0](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/e9de46cc-2ec9-4d7e-b697-9a9f19bea5d4)
更新到win11最新版本后弹幕字体显示异常

### 操作步骤

```plain text
1.打开直播间
2.打开弹幕
3.弹幕字体异常
```

### 期望结果

了解问题发生的原因，找到修复字体显示的办法

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装, 脚本安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 11 23H2 22631.3527

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
直播和视频的弹幕字体都这样吗，如果视频弹幕引擎设置为寒霜弹幕使的话再看视频呢（直播的弹幕引擎暂时无法设置

**Comment by thouser8** [comment]
> 直播和视频的弹幕字体都这样吗，如果视频弹幕引擎设置为寒霜弹幕使的话再看视频呢（直播的弹幕引擎暂时无法设置

视频的弹幕引擎为寒霜弹幕使就正常，设置为NSDanmaku就会和直播一样出现此问题

**Comment by ywmoyue** [comment]
@thouser8  麻烦测试一下设置弹幕字体后问题是否仍然存在，https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.1

字体名在C:\Windows\Fonts中找到

**Comment by ywmoyue** [comment]
播放器中弹幕设置

**Comment by thouser8** [comment]
> 播放器中弹幕设置

![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/d07adbd8-a59f-49de-ae01-24e6892d6d7c)
卸载重新用脚本安装了一遍也没找到

**Comment by ywmoyue** [comment]
视频播放器中的弹幕设置，直播中的忘记改了 
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/fb6bd16a-44e2-41bc-b35c-e35f08d14e5e)

**Comment by thouser8** [comment]
> 视频播放器中的弹幕设置，直播中的忘记改了 ![image](https://private-user-images.githubusercontent.com/28388300/327487564-fb6bd16a-44e2-41bc-b35c-e35f08d14e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjM5MzAsIm5iZiI6MTcxNDY2MzYzMCwicGF0aCI6Ii8yODM4ODMwMC8zMjc0ODc1NjQtZmI2YmQxNmEtNDRlMi00MWJjLWIzNWMtZTM1ZjA4ZDE0ZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzQ0ODI0ZWFjN2UyNjhjNjQxYzc1YzdmNDc5NzJjZWU1NTlhYmZiZGFjNmQ4M2NkYjVjZDIzNzFjYzA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzTMHv1LRAAKop_izvCJ6D09oS96zsGLNlUdkHx1O5g)

![966ebbb1d2b9519b2703716cc14ae5e3](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/b295c5ae-2c50-4475-ab3e-e0dbd8943bbe)
p1为使用NSDanmaku引擎时，p2为使用寒霜弹幕使引擎时，字形问题基本解决了，不过不知道为什么字体大小会不一样

**Comment by thouser8** [comment]
> 两个引擎的字体大小用的同一个设置项但不是完全对应的

了解了，感谢开发和解答！

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3  麻烦测下直播中的弹幕字体设置功能

**Comment by thouser8** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3 麻烦测下直播中的弹幕字体设置功能

试了下字体设置没什么问题，不过当设置为寒霜弹幕使时，有其他一些问题：
1.同屏弹幕重叠很严重；
2.点击弹幕开关可以关弹幕，无法开弹幕，只能用快捷键D开关。
暂时发现这两个问题，设置为NSDanmaku时都不会发生。
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/4dd72233-bfc8-4858-ad62-50d820b7feaa)

**Comment by thouser8** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3 麻烦测下直播中的弹幕字体设置功能

补充一点，NSDanmaku播放了一段时间后会有几分钟的弹幕延迟

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 可以再测一下

**Comment by thouser8** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 可以再测一下

寒霜弹幕使的弹幕延迟基本没问题了，试了下和另一个三方直播软件打开同一个直播间，这边的弹幕基本只比那边慢1秒左右；
同屏弹幕重叠问题在软件切换至后台再切回来后依然会存在
![image](https://github.com/ywmoyue/biliuwp-lite/assets/83090571/72849acd-f964-4f74-8c26-7263bcd0a6b4)
NSDanmaku貌似弹幕延迟比寒霜更低，而且切到后台切回来也不会有弹幕堆叠问题

**Comment by ywmoyue** [comment]
弹幕重叠问题暂时没法解决

**Comment by thouser8** [comment]
> 弹幕重叠问题暂时没法解决

或许可以增加一个限制直播同屏弹幕数量的功能？不过目前也不影响使用

**Comment by thouser8** [comment]
> 弹幕重叠问题暂时没法解决

或许可以增加一个限制直播同屏弹幕数量的功能？不过目前也不影响使用
