### ISSUE TITLE
关于播放位于播放列表（合集）中的视频时的问题

### ISSUE THREAD

**Issue by RBHakureiReimu** [ywmoyue/biliuwp-lite#610]
### Bug 描述

在首页或动态打开一个位于播放列表（合集）内的视频，并将该视频播放完毕时，应用不会自动向下播放位于播放列表内的、在刚播放完毕视频后的下一个视频，并且在该状态下切换到“播放列表”页面时，发现被应用识别为刚播放完视频后应播放的下一个视频的，是该列表的正数第二个视频。

在问题页面手动选择合集内任意视频后，便可以正常的按照顺序播放下去

### 操作步骤

```plain text
1.打开应用
2.在动态或首页打开任意一个位于合集内的视频
3.播放完打开的视频
4.复现bug
```

### 期望结果

在动态或首页中点击进入并播放完播放列表（合集）内任意视频后，可以正常的按照合集顺序继续播放下一个合集内视频

### 截图

![屏幕截图 2024-04-30 105534](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/7ce040a6-76e2-4f7e-a743-2b6e97b20897)
如上图所示，在任意地方打开一个合集视频（非仅合集有此问题）
![屏幕截图 2024-04-30 105549](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/2a7ec2de-0f99-4795-9375-2df38c5d0ab2)
如上图所示，该视频播放完毕后，应用没有继续向下播放下一条视频，而是直接跳转到该合集内第二条视频，与此同时该应用也没有播放顺序错误的第二条视频。
![屏幕截图 2024-04-30 105600](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/d55bee7d-0d7e-482e-9bb2-fc5910b31a2d)
如上图所示，该视频顺序位置位于合集内倒数第三个。

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 11 24H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 备注

这个bug好像有快小半年到一年了吧

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3 @RBHakureiReimu 麻烦测一下

**Comment by RBHakureiReimu** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3 @RBHakureiReimu 麻烦测一下

现状是播完就停止播放了，虽然不会莫名跳转到列表内的第二个视频，但也不会继续往下播放。哪怕手动选了下一集也不会连续播放
![屏幕截图 2024-05-10 235130](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/5fe13401-fa01-4e1e-bb86-38207906cb39)

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 可以再测一下

**Comment by RBHakureiReimu** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 可以再测一下

这回确实没问题了，大佬牛逼！！！
