### ISSUE TITLE
关于添加弹幕屏蔽词及正则屏蔽后，播放视频不显示弹幕的问题

### ISSUE THREAD

**Issue by RBHakureiReimu** [ywmoyue/biliuwp-lite#611]
### Bug 描述

在应用中添加大量屏蔽词或正则屏蔽，或通过B站屏蔽词云同步大量屏蔽词后，应用播放视频时会不显示弹幕

### 操作步骤

```plain text
1.打开应用
2.添加大量正则、屏蔽词或云同步其他设备屏蔽词
3.播放任意视频
4.复现bug
```

### 期望结果

添加大量弹幕屏蔽词后，播放视频时可以显示弹幕（毕竟B的弹幕风气有目共睹，不多加点屏蔽词弹幕真看不了一点）

### 截图

![屏幕截图 2024-04-30 115745](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/5d655434-eeec-4b65-9a20-5289b89384c9)
如上图所示，已在应用内添加了屏蔽词
![屏幕截图 2024-04-30 115820](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/1b4caf47-9fed-4ac8-98b0-3f7f8f67c443)
如上图所示，明明已经开启弹幕，该视频也有8000多条弹幕，但是应用不显示弹幕
下面两张图是对照组
![1714449743200](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/3781d1a4-00fa-48aa-b18d-93b7b530a177)
![1714449743205](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/1a9d973d-d516-4595-ae9f-d45865bea8e1)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 11 24H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 备注

这个bug应该也挺长时间了，在屏蔽词和正则数量多的时候就会稳定复现

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
我把弹幕筛选逻辑抽出来做了demo，麻烦你用这个demo测一下 @RBHakureiReimu  https://ywmoyue.github.io/demo/bililite-danmaku-filter-demo/

**Comment by RBHakureiReimu** [comment]
> 我把弹幕筛选逻辑抽出来做了demo，麻烦你用这个demo测一下 @RBHakureiReimu https://ywmoyue.github.io/demo/bililite-danmaku-filter-demo/

大佬，你这个demo貌似只能一条一条加啊，有一说一，一条一条加80份有点太困难了😂麻烦大佬让这个demo能直接导入B站官方网页版导出的json文件吧，辛苦大佬了

![image](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/074fb5c9-ca3c-4f59-aa37-6551f85108a4)

![image](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/f0243dce-8364-4216-86be-af34825626ce)

**Comment by ywmoyue** [comment]
> > 我把弹幕筛选逻辑抽出来做了demo，麻烦你用这个demo测一下 @RBHakureiReimu https://ywmoyue.github.io/demo/bililite-danmaku-filter-demo/
> 
> 大佬，你这个demo貌似只能一条一条加啊，有一说一，一条一条加80份有点太困难了😂麻烦大佬让这个demo能直接导入B站官方网页版导出的json文件吧，辛苦大佬了
> 
> ![image](https://private-user-images.githubusercontent.com/45761551/334658796-074fb5c9-ca3c-4f59-aa37-6551f85108a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjAxNjEsIm5iZiI6MTcxNjk1OTg2MSwicGF0aCI6Ii80NTc2MTU1MS8zMzQ2NTg3OTYtMDc0ZmI1YzktY2EzYy00ZjU5LWFhMzctNjU1MWY4NTEwOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA1MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGVlZDdlODBlMDVhMGRjZjc1ZjA0NDlkMmUwNDI5NzE0MzE3OTQ3NTQ3NWY4YjhmZWYxOGI4NWE2NGQ5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._HRhyiU5TNWsUBPU9TrlIFLunl2fqpGpv5bxBIw9TPE)
> 
> ![image](https://private-user-images.githubusercontent.com/45761551/334658822-f0243dce-8364-4216-86be-af34825626ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjAxNjEsIm5iZiI6MTcxNjk1OTg2MSwicGF0aCI6Ii80NTc2MTU1MS8zMzQ2NTg4MjItZjAyNDNkY2UtODM2NC00MjE2LTg2YmUtYWYzNDgyNTYyNmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA1MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMmNkOWI4MzYzZGE2OTg5ODhmZDFkNGExNzA0ZDU5YmIyMzgyN2ZlYWVhNDE3YTI4MWFiZmYyODA1NTVhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IINvTG33BTDXDxVHTL4XfkPXP1jG94HWsuY7W1KQfQk)

行，我看看

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu demo加上导入功能了

辛苦大佬，刚试了一下，demo是没问题的，但是之前就因为这个bug把云端在内的屏蔽词全删了，只留了正则（只留正则也有这问题，后面删的只剩10条左右才正常），再加上之前导入屏蔽词那个网站找不到了，所以屏蔽词暂时就测不了了

![image](https://github.com/ywmoyue/biliuwp-lite/assets/45761551/c1a88205-fef8-45f9-b962-26574b4e63de)

**Comment by ywmoyue** [comment]
@RBHakureiReimu 弹幕引擎用的是寒霜弹幕使还是NSDanmaku

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu 弹幕引擎用的是寒霜弹幕使还是NSDanmaku

刚试了一下，俩都有问题

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu 弹幕引擎用的是寒霜弹幕使还是NSDanmaku

必须得删的只剩下十几二十条正则才不会卡死，两个都是

**Comment by ywmoyue** [comment]
demo中的弹幕来自这个视频：BV1xx411c7Xg，也可以看看

你要说卡死的话，不会是性能问题吧，我后面出个临时版本在筛选弹幕这里加个日志看看

**Comment by RBHakureiReimu** [comment]
> demo中的弹幕来自这个视频：BV1xx411c7Xg，也可以看看
> 
> 你要说卡死的话，不会是性能问题吧，我后面出个临时版本在筛选弹幕这里加个日志看看

我说的“卡死”只是我个人猜想：“是不是受限于UWP平台本身机能限制，屏蔽词一多弹幕引擎就卡死了。”是这个意思，视频本身是正常播放的

**Comment by RBHakureiReimu** [comment]
> demo中的弹幕来自这个视频：BV1xx411c7Xg，也可以看看
> 
> 你要说卡死的话，不会是性能问题吧，我后面出个临时版本在筛选弹幕这里加个日志看看

视频是正常流畅播放的，只是屏蔽词一多就不会显示弹幕

**Comment by ywmoyue** [comment]
@RBHakureiReimu 我这边测了下添加纯数字正则从1到70共70个，但是仍然是正常显示弹幕的，方便将你的这个block.json发出来这边用来测下吗

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu 我这边测了下添加纯数字正则从1到70共70个，但是仍然是正常显示弹幕的，方便将你的这个block.json发出来这边用来测下吗

[bilibili.block.json](https://github.com/ywmoyue/biliuwp-lite/files/15483222/bilibili.block.json)

**Comment by ywmoyue** [comment]
我这边导入你这份文件后播放BV1xx411c7Xg，弹幕仍然正常显示，后续我这边加日志看下吧

**Comment by ywmoyue** [comment]
@RBHakureiReimu  这边测试发现是`/.\\1{16}/`这条正则导致的，而且这条正则在你的json文件中有两条

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu 这边测试发现是`/.\\1{16}/`这条正则导致的，而且这条正则在你的json文件中有两条

啊这……但是在官方平台就没有这问题，应该是官方自动屏蔽了有问题的正则了吧😂

**Comment by ywmoyue** [comment]
@RBHakureiReimu 麻烦用该版本重新同步或导入一次试试 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3202

这边处理了同步或导入时移除非法正则

**Comment by RBHakureiReimu** [comment]
> @RBHakureiReimu 麻烦用该版本重新同步或导入一次试试 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3202
> 
> 这边处理了同步或导入时移除非法正则

大佬，这边试了一下，导入含有非法正则的时候确实自动删掉了，辛苦大佬了。
