### ISSUE TITLE
直播弹幕延迟

### ISSUE THREAD

**Issue by RicardoDENG** [ywmoyue/biliuwp-lite#613]
### Bug 描述

直播弹幕貌似又开始有延迟了，之前提出后修正了，最新版本，有延迟还是有点影响观感

### 操作步骤

```plain text
点开直播间，观看10-30分钟，会出现弹幕滞后7-10秒，弹幕讨论内容与直播内容明显错位
```

### 期望结果

弹幕延迟恢复正常

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 设备类型

笔记本

### 设备架构

x64, Arm64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
确实非常奇怪，明明直播的弹幕部分代码已经很久没动过了。目前猜测是否连接b站下发的弹幕服务器会好一点？ 现在使用的是一个固定的b站弹幕服务器

**Comment by RicardoDENG** [comment]
> 确实非常奇怪，明明直播的弹幕部分代码已经很久没动过了。目前猜测是否连接b站下发的弹幕服务器会好一点？ 现在使用的是一个固定的b站弹幕服务器

我发现蓝光画质及以下延迟问题会好很多，不知道是不是这方面原因
