### ISSUE TITLE
关于分P标题

### ISSUE THREAD

**Issue by JiegeSTU** [ywmoyue/biliuwp-lite#615]
### 问题描述

<img width="353" alt="无标题" src="https://github.com/ywmoyue/biliuwp-lite/assets/139949948/65904da5-4fe2-44a8-8004-d3d1df3fcf50">
如图,分P视频的标题如果过长就无法显示完全,需要拉宽详情页,但拉宽之后又会自适应导致显示列数更多,仍然无法显示完全

### 描述解决方案

增加选项让详情页显示列数固定而不是自适应

### 代码贡献

否

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.30.3104 麻烦测一下

**Comment by ywmoyue** [comment]
没有回复，我这边就先发版本了，有问题下个版本再处理
