### ISSUE TITLE
一个未适配的动态

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#618]
### Bug 描述

此用户的5月6日的一条动态显示未适配：
https://space.bilibili.com/49839041/dynamic

看起来像课程一类的

### 操作步骤

```plain text
略
```

### 期望结果

正常显示该动态

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这个动态适配了，但是视频还没适配，后面再看看吧
