### ISSUE TITLE
4.6.0.1 弹幕会溢出视频范围，全屏界面上方有白条，多个选项卡间没有分割线

### ISSUE THREAD

**Issue by wzaiz** [ywmoyue/biliuwp-lite#62]
![Snipaste_2023-04-29_22-19-16](https://user-images.githubusercontent.com/82254937/235308019-360d4093-6818-4c1e-a0a0-f6d7f643471b.png)
![Snipaste_2023-04-29_22-28-19](https://user-images.githubusercontent.com/82254937/235308169-126ab38e-cdf6-456b-a3e1-75ee9213b711.png)

**Comment by ywmoyue** [comment]
请问您用的什么版本的操作系统，显示器分辨率是多少

**Comment by stnfttg** [comment]
windows 11 22621.1635，选项卡这个问题没有，窗口最大化还是能辨识的，弹幕这个倒是随时都能复现，不点击铺满窗口，弹幕还是出现在详情下层

**Comment by ywmoyue** [comment]
弹幕会溢出视频范围这个问题单独拉个issue处理吧，这里讨论下全屏白条问题
https://github.com/ywmoyue/biliuwp-lite/issues/65

**Comment by ywmoyue** [comment]
能否截图下下载视频全屏播放呢

我想对比下载视频的全屏上方白条和在线视频的全屏上方白条的大小

**Comment by wzaiz** [comment]
> 能否截图下下载视频全屏播放呢 @wzaiz
> 
> 我想对比下载视频的全屏上方白条和在线视频的全屏上方白条的大小
非常抱歉，五一没用电脑。我刚才想要复现白条的问题，但是在线视频白条自己消失不见了，下载视频的白条如下
![下载视频的白条问题](https://user-images.githubusercontent.com/82254937/236381987-3accc35c-5596-4284-944e-df317a2cccd4.png)
电脑版本是win10 (19045.2846)，分辨率是1080p，软件版本是4.6.0.1

**Comment by ywmoyue** [comment]
标签栏问题改在此处讨论，当前issue关闭：https://github.com/ywmoyue/biliuwp-lite/discussions/123
