### ISSUE TITLE
点击评论区时间快速空降

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#640]

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3201

@youhunluanma @Shaddoll126 功能已实现，麻烦验证一下

**Comment by Shaddoll126** [comment]
https://b23.tv/BV1Fz4y117pV  刚才试了一下，可以实现点击评论区时间空降到对应时间
