### ISSUE TITLE
CC 字幕样式美化

### ISSUE THREAD

**Issue by pheotry** [ywmoyue/biliuwp-lite#645]
### 问题描述

现在这种CC字幕加阴影的样式实在是有点不好看

### 描述解决方案

感觉可以加个背景，类似于进度调整这种白色背景或者和官方网站的那种半透明黑色背景。

图一是现在的样式，图二白色背景显示效果, 图三是B站网页样式。

另外如果可以使用快捷键比如 `C` 或 `Shift + C` 快速开关字幕就好了

![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/d554c12d-e25d-49f0-b9a1-cb520637b4b0)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/1efcfd0c-be6b-4e11-90d7-f0d9d09a3214)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/34a36efa-c99a-4b03-bd06-27a067c8286d)

### 代码贡献

否

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3202 @pheotry 麻烦测一下，播放器中字幕设置里设置描边颜色为透明，边框颜色填一个半透明的HEX值应该就是你要的效果

**Comment by pheotry** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3202 @pheotry 麻烦测一下，播放器中字幕设置里设置描边颜色为透明，边框颜色填一个半透明的HEX值应该就是你要的效果

可以
显示效果还行
![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/b8d43cfc-9fb9-4dc2-b774-a1373275bc3c)
![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/8689d8c9-c779-4db3-a76c-fd8c65afad03)

**Comment by pheotry** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.31.3202 @pheotry 麻烦测一下，播放器中字幕设置里设置描边颜色为透明，边框颜色填一个半透明的HEX值应该就是你要的效果

就是好像不居中
![image](https://github.com/ywmoyue/biliuwp-lite/assets/43376740/0d840a1f-89c7-44bb-8b33-004f499a8a41)
