### ISSUE TITLE
点击时间跳转功能可以有一些外观优化的点

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#654]
### 问题描述

我想要一些点击时间跳转按钮的新功能，以便于用户理解和更好的使用。

### 描述解决方案

1. 中文冒号也能识别，例如：`1：45：42`
2. 仿照视频跳转的按钮，在按钮前加个emoji以区分普通文字与跳转，更加美观？例如：`🪂 23:33` 
3. 中文描述也能识别，例如： `一分二十秒` or `1分20秒` (可能比较难且易混淆，此条也可不做）

### 代码贡献

否

**Comment by ywmoyue** [comment]
第一第二点都行，第三点就算了吧
