### ISSUE TITLE
评论空降识别时间格式有问题

### ISSUE THREAD

**Issue by Jiagu1218** [ywmoyue/biliuwp-lite#655]
### Bug 描述

评论区空降时间格式有问题，无法正确识别

### 操作步骤

```plain text
示例视频评论区：https://b23.tv/BV1mb421e7wC
```

### 期望结果

正确识别空降时间节点

### 截图

![image](https://github.com/ywmoyue/biliuwp-lite/assets/38897701/fb640d32-83f8-47eb-9ef4-ef2055e34839)
接口返回的字符串：
![image](https://github.com/ywmoyue/biliuwp-lite/assets/38897701/e99b8b53-9b33-4400-9499-2eb1a958d753)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

win11 24H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这是因为这个评论的时间与文字之间没有空格，已经修复了，没有跟前一个临时版本发出去
