### ISSUE TITLE
因为近期特殊原因导致弹幕消失

### ISSUE THREAD

**Issue by 06333** [ywmoyue/biliuwp-lite#656]
### Bug 描述

因该是临近高考所以b站把弹幕关了，网页的聊天区依然能显示弹幕，但是应用内的互动区无法显示弹幕

### 操作步骤

```plain text
1. 打开应用
2. 进入一个直播间
3. 发现问题
```

### 期望结果

正常显示弹幕或者正常显示互动区

### 截图

![QQ截图20240604030717](https://github.com/ywmoyue/biliuwp-lite/assets/130553938/e74723e9-5bf6-4adf-897f-bec45cebafa2)
![QQ截图20240604030751](https://github.com/ywmoyue/biliuwp-lite/assets/130553938/8d66f85a-b3c6-4f91-8b70-1b8d8950c861)

### 日志

[20240604.log](https://github.com/user-attachments/files/15538683/20240604.log)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

win10 22H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 备注

估计过段时间就好了所以修不了也没事

### 代码贡献

我更擅长发现问题

**Comment by 06333** [comment]
我的版本: 4.6.31.3201

**Comment by GD-Slime** [comment]
看了一下网页端，b站在近期将`DANMU_MSG`这个cmd改为了`DANMU_MSG:4:0:2:2:2:0`，简单改个匹配规则就行。
参考 https://github.com/starknt/tiny-bilibili-ws/issues/1 这种问题好像以前也出现过，过几天度过敏感时期就改回来了。

**Comment by 06333** [comment]
现在貌似是好了，不知道为什么这次这么快
