### ISSUE TITLE
调整视频详情页面收藏按钮展开收藏夹列表后保存按钮的位置

### ISSUE THREAD

**Issue by hy13467966269** [ywmoyue/biliuwp-lite#682]
### 问题描述

在当前版本展开收藏夹列表后，如果自己建立的收藏夹过多，需要手动下滑后才会显示出保存按钮

### 描述解决方案

将保存按钮单独做一行，使得其独立于上面的收藏夹列表而存在

### 代码贡献

否

**Comment by ywmoyue** [comment]
@hy13467966269  试试 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.33.3401
