### ISSUE TITLE
在动态页面查看评论时点击图片会出现在评论窗口下层

### ISSUE THREAD

**Issue by PIut02** [ywmoyue/biliuwp-lite#69]
图片会被评论窗口遮挡，如图
版本为4.6.0.2
![image](https://user-images.githubusercontent.com/39442130/235746784-e5e12877-278d-4bbd-9bb3-cf7026b05ed6.png)

**Comment by PIut02** [comment]
此外，这个页面的顶部按钮图标没有居中
![image](https://user-images.githubusercontent.com/39442130/235747201-a505f044-ef1a-4310-acc4-8af9c651b59d.png)

**Comment by ywmoyue** [comment]
动态页查看评论用的ContentDialog，这玩意不好整，可能要改其他方式了，下个版本我暂时先将这块禁了吧
