### ISSUE TITLE
首页推荐直播间反复出现并且无法取消

### ISSUE THREAD

**Issue by RicardoDENG** [ywmoyue/biliuwp-lite#695]
### Bug 描述

如标题

### 操作步骤

```plain text
一旦首页推荐了一个直播间，往下刷的时候就会反复出现，哪怕重启应用也还是有，并且右键无法选不感兴趣
```

### 期望结果

推荐直播间短时间内只出现一次，并且右键可以点击不感兴趣取消推荐

### 截图

![ZGD9`3DAI LYR_{NY~K%~ W](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/3a2c9b24-eb15-476a-8d26-42547e9919eb)
![()$6K{$B)AV 6BE8E~RZSF1](https://github.com/ywmoyue/biliuwp-lite/assets/126185560/821a1077-9bcf-45fb-8e4f-4d5a4a2bf5c2)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
@RicardoDENG 麻烦给一下日志，我需要确认直播间反复出现的问题是否因为处理这个问题导致的 
日志在软件帮助页最下面能找到
https://github.com/ywmoyue/biliuwp-lite/issues/669

**Comment by RicardoDENG** [comment]
[20240703.log](https://github.com/user-attachments/files/16077887/20240703.log)

**Comment by ywmoyue** [comment]
![image](https://github.com/ywmoyue/biliuwp-lite/assets/28388300/369ca610-af34-4f12-bd95-271271330588)

@RicardoDENG 请不要把这个选项关掉，刚刚的日志我先删了，后面有空请修改一次密码确保账号安全 😰

**Comment by ywmoyue** [comment]
看了下应该是代码问题导致令牌在报错时被打印到日志上了，是我的问题，抱歉

**Comment by ywmoyue** [comment]
> @RicardoDENG 麻烦给一下日志，我需要确认直播间反复出现的问题是否因为处理这个问题导致的 日志在软件帮助页最下面能找到 #669

确认了下不是这个问题导致的，每次请求首页推荐视频列表都有上一次的信息

我看一下直播间取消这个问题怎么处理吧

**Comment by ywmoyue** [comment]
@RicardoDENG 看看能否用该版本的内容过滤功能处理这个问题，比如将这个up主加入过滤规则中 https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.0

**Comment by RicardoDENG** [comment]
可以的，已经解决，可以收起这项bug了
