### ISSUE TITLE
标签页功能优化

### ISSUE THREAD

**Issue by gcl-l** [ywmoyue/biliuwp-lite#721]
### 问题描述

1.标签页长度固定，
方便打开多个标签页时快速关闭

2.鼠标悬浮在标签页上时-
右键点击标签页-
不跳转界面，直接关闭标签页

3.鼠标在标签栏滚动时能切换标签页，
或者监听快捷键，按住shift时滚动鼠标上下能切换左边或右边标签页
![PixPin_2024-07-22_05-49-49](https://github.com/user-attachments/assets/59ddfff0-2777-4889-81a3-39e988674138)

这样就能想浏览器一样便携操作很多

### 描述解决方案

。

### 代码贡献

否

**Comment by gcl-l** [comment]
标签页长度如果还能自己设置固定长度就好了，自己调长度需求

**Comment by ywmoyue** [comment]
这个issue先做第一点，后面的需要另外开issue
