### ISSUE TITLE
4K特别卡 哪里能优化呢

### ISSUE THREAD

**Issue by gcl-l** [ywmoyue/biliuwp-lite#723]
### 问题描述

1080P高帧和1080以及以下都流畅，
就切换4K卡的特别厉害，或者加载不出来一直转圈圈但是弹幕能动。。。

电脑r5 5600x处理器
rx 5700 显卡
千兆宽带，网线直连，网盘和steam下载都飞速，网页端看4k也不会卡

就是uwp遇到这种卡顿情况

### 描述解决方案

。

### 代码贡献

否

**Comment by gcl-l** [comment]
我是播放【异环】的pv视频察觉到的，可以用这个视频做测试

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.4 试试4.7.4设置播放器类型为FFmpegInterop  @gcl-l
