### ISSUE TITLE
很多UP的视频列表会报错

### ISSUE THREAD

**Issue by CoderYiXin** [ywmoyue/biliuwp-lite#74]
点UP主头像的视频列表为空，提示报错

**Comment by CoderYiXin** [comment]
![企业微信截图_20230505133654](https://user-images.githubusercontent.com/30307554/236384306-925939c0-68b6-4013-a722-0d704cc3ad78.png)

**Comment by ywmoyue** [comment]
相同问题： https://github.com/ywmoyue/biliuwp-lite/issues/61

预发布版本4.6.0.2已修复https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.6.0.2 ，可等待正式版或直接安装该版本
