### ISSUE TITLE
播放结束闪退

### ISSUE THREAD

**Issue by A1917** [ywmoyue/biliuwp-lite#740]
### Bug 描述

播放视频结束后几秒钟闪退

### 操作步骤

```plain text
播放视频进度条跑完触发闪退
```

### 期望结果

增加稳定性

### 日志

[20240804.log](https://github.com/user-attachments/files/16487025/20240804.log)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
看日志应该是4.7.0的版本，试试4.7.0.102

如果仍然闪退再提供日志
