### ISSUE TITLE
使用代理搜索时出现-400错误

### ISSUE THREAD

**Issue by Re-hd** [ywmoyue/biliuwp-lite#744]
### Bug 描述

如题，我使用的是以下这篇文章的方法：https://github.com/Richasy/Bili.Uwp/wiki/%E6%9E%84%E5%BB%BA%E7%95%AA%E5%89%A7%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1
现在没有从0创建的选项了，我用的自定义运行时，填入链接后出现-400错误
![image](https://github.com/user-attachments/assets/3e3dddf0-d578-4a60-ad77-a6a4e41dab26)
阿里云那边显示有调用次数
![image](https://github.com/user-attachments/assets/e06fb29d-339c-4f7b-b06c-0b16b6ae58fe)
能看一下问题在哪里吗，谢谢

### 操作步骤

```plain text
1.打开应用，
2.设置代理地址，
3.返回搜索任意番剧，
出现-400错误
```

### 期望结果

能够正常显示搜索结果

### 截图

[code.zip](https://github.com/user-attachments/files/16495967/code.zip)
函数的zip包

### 日志

[20240805.log](https://github.com/user-attachments/files/16495983/20240805.log)

### 应用来源

Github/其他Github镜像站

### 安装方式

appx直接安装

### 系统版本

其它 (需注明)

### 其它系统版本

windows11 23H2

### 设备类型

笔记本

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这里使用的是适配哔哩漫游的代理，如果要使用自行部署的代理服务的话应该在github内搜索biliroaming server的相关项目

**Comment by Re-hd** [comment]
OK感谢
