### ISSUE TITLE
填弹幕时意外触发快捷键

### ISSUE THREAD

**Issue by ufvi** [ywmoyue/biliuwp-lite#754]
### Bug 描述

在输入弹幕内容时，很容易触发快捷键，如'W'、'O'，导致了意外的结果

### 操作步骤

```plain text
1. 打开视频进入弹幕输入框
2. 按下的按钮包含快捷键时
```

### 期望结果

输入弹幕时屏蔽快捷键

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by slinar** [comment]
直播间输入弹幕也是相同的情况
