### ISSUE TITLE
修改安装教程

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#762]
### Bug 描述

ClashForWindows UWP解限工具无法解除使用 Install.ps1 安装的 BiliBili-Lite

另外最新Beta无法直接通过msix安装 (Windows11)

### 解决方案
```plain text

 脚本安装完后使用 msix 包覆盖安装一遍


```

### 期望结果

.

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by TPAXcc** [comment]
暂时废弃. 经测试以上操作后依然无法访问互联网

**Comment by ywmoyue** [comment]
可以提PR修改https://github.com/ywmoyue/biliuwp-lite/blob/dev/document/install-readme.md

**Comment by TPAXcc** [comment]
> 可以提PR修改https://github.com/ywmoyue/biliuwp-lite/blob/dev/document/install-readme.md

现在我也不确定到底是怎么弄了，又自己好了（
复现不了

**Comment by ywmoyue** [comment]
那先close了
