### ISSUE TITLE
播放视频中左右快进可能使右侧页面左右滚动

### ISSUE THREAD

**Issue by Chronodeus** [ywmoyue/biliuwp-lite#763]
### Bug 描述

在播放视频中按左右方向键调整视频进度时，有一定概率会使右侧的详情、评论、推荐等页面随之左右切换。

暂不明该bug出现时机与原因，但一般刚打开app一段时间内不会出现此bug

### 操作步骤

```plain text
1.打开应用
2.播放视频
3.按左右键调整进度
4.有概率使右侧详情等页面随之切换
```

### 期望结果

在播放中，右侧页面不随左右键切换

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

其它 (需注明)

### 其它系统版本

Windows 10 22H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这是因为控制焦点在右侧tab上

**Comment by Chronodeus** [comment]
> 这是因为控制焦点在右侧tab上

可是鼠标点进播放器内部了还是会这样😢
