### ISSUE TITLE
部分杜比视界视频无法加载

### ISSUE THREAD

**Issue by ce9suo** [ywmoyue/biliuwp-lite#767]
### Bug 描述

有部分杜比视界的视频和所有HDR视频能正常加载，但是部分杜比视界无法加载一直显示正在缓冲，且视频为大陆视频无代理。网络通畅，可如果将将此无法正常播放的杜比视频切换至4K 能正常播放（此视频在其他设备能正常播放杜比）

### 操作步骤

```plain text
点开视频切换到杜比视界
```

### 期望结果

希望能够正常看杜比视界

### 应用来源

Github/其他Github镜像站

### 系统版本

其它 (需注明)

### 其它系统版本

24H2

### 设备类型

平板, 笔记本

### 设备架构

x64, Arm64

### 应用架构

Arm64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.4 试试4.7.4设置播放器类型为FFmpegInterop  @ce9suo

**Comment by ce9suo** [comment]
感谢 能够正常看了

**Comment by ce9suo** [comment]
现在有个新问题，每个视频在播放6分钟后他会自动将进度条拉至最后，去播放下一个视频

**Comment by ywmoyue** [comment]
确实有这个问题，在我这里不是必现的，后面看看怎么处理

**Comment by ywmoyue** [comment]
@ce9suo 有哪个视频能复现这个问题吗

> 现在有个新问题，每个视频在播放6分钟后他会自动将进度条拉至最后，去播放下一个视频

**Comment by ce9suo** [comment]
我试过好几个视频都会出现，最初发现的是linksphotograph最新视频在杜比视界下 突然会结束播放
