### ISSUE TITLE
打开app时闪退

### ISSUE THREAD

**Issue by Chronodeus** [ywmoyue/biliuwp-lite#792]
### Bug 描述

点开app时会卡死，然后闪退。概率触发且一旦触发就得连续触发几次后才能正常进入

### 操作步骤

```plain text
1.打开应用
2.闪退
3.重复几次后才能正常进入应用
```

### 期望结果

正常进入

### 截图

![PixPin_2024-08-26_13-43-46_2_2](https://github.com/user-attachments/assets/8d277c03-7c14-4166-872d-f7b689c5b60c)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 其它系统版本

Windows 10 22H2

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
如果能正常进入的话麻烦将日志级别设置为Trace然后再次复现后提供一下日志

**Comment by Chronodeus** [comment]
[20240826.log](https://github.com/user-attachments/files/16744837/20240826.log)

**Comment by ywmoyue** [comment]
看日志中的错误似乎是ImageEx控件导致的崩溃，我后面尝试处理一下

**Comment by Chronodeus** [comment]
试了几次都没再复现了，应该是可以了
