### ISSUE TITLE
点按方向键步进分档

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#808]
### 问题描述

每按3次将步进挡位+1

第一档 步进1秒
第二档 步进3秒
第三档 步进5秒
第四档 步进10秒
第五档 步进30秒
第六档 步进60秒
第七档 步进600秒
第八档 步进1800秒
第九档 步进3600秒
...(再高挡位就是再100h+的视频才有意义了）

### 描述解决方案

.

### 代码贡献

是

**Comment by ywmoyue** [comment]
这太复杂了，应该没有别的播放器有这么做过吧，要快速快进不如把持续快进开起来设置一个不冲突的键位

**Comment by TPAXcc** [comment]
> 这太复杂了，应该没有别的播放器有这么做过吧，要快速快进不如把持续快进开起来设置一个不冲突的键位

印象中是有的，估计是某个开源播放器有这功能，要不你整三档也行，目前这个快进步长实在是太短了

**Comment by TPAXcc** [comment]
而且这个需求很难实现吗？不是一个循环就行了

**Comment by TPAXcc** [comment]
using System;

class Program
{
    static void Main()
    {
        int position = 1; // 初始档位设为1
        int steps = 3; // 每按3次改变一次档位

        for (int i = 0; i < 10; i++) // 这里假设我们测试按下按钮10次
        {
            if (i % steps == 0 && i != 0) position++; // 每按3次档位+1
            Console.WriteLine($"档位: {position}, 步进时间: {CalculateStepTime(position)}秒");
        }
    }

    static int CalculateStepTime(int pos)
    {
        if (pos >= 1 && pos <= 2) return pos * pos;
        else if (pos == 3) return 5;
        else if (pos == 4) return 10;
        else if (pos <= 6) return 30 * (pos - 4) + 10;
        else if (pos <= 9) return 60 * (pos - 6) + 60;
        else return 0; // 如果超过范围或输入错误
    }
}

**Comment by TPAXcc** [comment]
https://github.com/ywmoyue/biliuwp-lite/pull/810
