### ISSUE TITLE
win10无法安装

### ISSUE THREAD

**Issue by Haibaraxxx** [ywmoyue/biliuwp-lite#809]
### Bug 描述

powershell无法安装，显示缺少配置

### 操作步骤

```plain text
1.根据安装获取权限
2.运行脚本
3.报错，无法安装
```

### 期望结果

安装成功

### 截图

[](url)
![ZJ`P5J`)DR@TSI4PVT~AV%2](https://github.com/user-attachments/assets/ab1cafd7-c836-4df2-9c94-46a34b2426e8)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 10 1909 (Build 18363)

### 设备类型

笔记本

### 应用架构

x86, x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
1. 如果是x64架构的系统需要使用x64的安装包
2.如果确认是x86没问题需要麻烦截图发一下解压出来的文件夹中Dependencies/x86文件夹中的文件列表截图，Microsoft.NET.CoreRuntime.2.2.appx依赖包应该在这个路径下才对

**Comment by Haibaraxxx** [comment]
解压问题，原来解压出来没有Dependencies文件夹，更换解压软件后正常，目前已成功安装，感谢
