### ISSUE TITLE
选集界面错误换行

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#816]
### Bug 描述

<img width="245" alt="image" src="https://github.com/user-attachments/assets/e3a74a25-c1d0-4f7c-a2eb-8ccf1bfcc736">

### 操作步骤

```plain text
。
```

### 期望结果

。

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by TPAXcc** [comment]
经典修了一个bug新造一个（

**Comment by ywmoyue** [comment]
确实，前面只关注了分p数显示出来了就没管了

**Comment by TPAXcc** [comment]
> 确实，前面只关注了分p数显示出来了就没管了

😂
