### ISSUE TITLE
评论图片建议加个遮罩+错误提示，不然都不知道有到底没有图片，并且似乎图片加载还有点问题，经常闪退

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#82]
![图片](https://user-images.githubusercontent.com/91980905/236667431-681c75d4-88a5-41a3-a609-f4b4f6a65944.png)

**Comment by ywmoyue** [comment]
问下是哪个视频底下的评论图片有如题描述的问题

**Comment by TPAXcc** [comment]
> 问下是哪个视频底下的评论图片有如题描述的问题

阿姨历史记录不全，没翻到...不过这个似乎是偶发问题，等遇到再反馈吧，可以加个加载遮罩先
