### ISSUE TITLE
每次启动都会弹出报错信息"程序出现一个错误，已记录"

### ISSUE THREAD

**Issue by lucifere02** [ywmoyue/biliuwp-lite#827]
### Bug 描述

如题，截图和日志文件已附。

### 操作步骤

```plain text
打开应用即可见界面下方弹出报错信息。
```

### 期望结果

无报错信息弹出。

### 截图

![image](https://github.com/user-attachments/assets/a17ff371-132b-4a3a-9f1f-ee64845a7ef0)

### 日志

[20240925.log](https://github.com/user-attachments/files/17119451/20240925.log)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 10 21H1 (Build 19043)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
@lucifere02 试试4.7.4
