### ISSUE TITLE
支持修改缓存目录或在内存中缓冲视频

### ISSUE THREAD

**Issue by CirnoSalt** [ywmoyue/biliuwp-lite#831]
### 问题描述

最近使用过程中发现在观看较高画质视频时客户端会向系统盘大量写入缓存，并且观察到相同画质下写入量比网页版要高不少，系统盘如果是SSD这会导致一些不必要的寿命消耗，我尝试将WindowsTemp环境变量目录设置到内存盘中，但这个客户端似乎没有遵循环境变量，依然在向系统盘中写入缓存……

### 描述解决方案

能否支持自行设置缓存目录，或者优先向内存中写入播放缓冲数据呢？

### 附加信息

![屏幕截图 2024-09-26 223009](https://github.com/user-attachments/assets/b493a2a0-7935-4de2-890c-343d61317d97)

### 代码贡献

否

**Comment by ywmoyue** [comment]
确实有这个问题，看了下播放器没有相关的可以设置的api

晚点看看能不能处理

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.4 试试4.7.4设置播放器类型为FFmpegInterop @CirnoSalt

**Comment by CirnoSalt** [comment]
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.4 试试4.7.4设置播放器类型为FFmpegInterop @CirnoSalt

磁盘占用问题解决了，但是发现了新的bug，拖动进度条和键盘左右快捷键会直接跳回原位，只有点击进度条才能成功跳转……
