### ISSUE TITLE
开启使用下载索引设置项后下载视频无字幕

### ISSUE THREAD

**Issue by YFTX2015** [ywmoyue/biliuwp-lite#860]
### 问题描述

目前导出到本地的合并后的港澳台番剧，用第三方播放器播放没有字幕，希望解决这个问题。

### 描述解决方案

可参考云之幻开发的哔哩助手，他的app下载视频功能是点击下载按钮后自动"下载-合并-更名-导出"一条龙服务，并且导出的港澳台番剧用第三方播放器播放也能显示字幕。

### 代码贡献

否

**Comment by ywmoyue** [comment]
目前是有合并字幕的，没有字幕可能有bug或者字幕没有下载下来，你右键视频打开目录看下有没有srt字幕文件

**Comment by YFTX2015** [comment]
> 目前是有合并字幕的，没有字幕可能有bug或者字幕没有下载下来，你右键视频打开目录看下有没有srt字幕文件

你试试悲喜漁生（僅限港澳台地區）这部番，下载下来有.json字幕文件，但是合并导出后就是没有。

**Comment by ywmoyue** [comment]
@YFTX2015 你是否开了使用下载索引这个设置项，刚发现这里有bug，会导致下载视频没有字幕

**Comment by YFTX2015** [comment]
开了

**Comment by YFTX2015** [comment]
关了之后就能显示字幕了，然后我发现字幕是简中，这个合并导出是不是有繁化简的功能？

**Comment by ywmoyue** [comment]
> 关了之后就能显示字幕了，然后我发现字幕是简中，这个合并导出是不是有繁化简的功能？

有，代理设置中可以设置是否开启

**Comment by YFTX2015** [comment]
看到了
