### ISSUE TITLE
不记录视频播放进度和v4.6.0更新后只有480p的分辨率？

### ISSUE THREAD

**Issue by Ye-QAQ** [ywmoyue/biliuwp-lite#87]

**Comment by 52-0** [comment]
重登账号以后就可以切换分辨率了，但是还是不同步播放进度

**Comment by ywmoyue** [comment]
1. 视频播放进度记录会在应用内关闭视频标签页时触发，后续考虑加个关闭应用时触发
2. 分辨率问题相同Issue： https://github.com/ywmoyue/biliuwp-lite/issues/31 ，暂时没发现是什么原因导致的

**Comment by 52-0** [comment]
哦哦，感谢解答，我都不知道关闭视频标签页时触发

**Comment by ywmoyue** [comment]
请问下更新4.6.3后是否还会出现已登陆时分辨率只有480p的情况 @Ye-QAQ

**Comment by Ye-QAQ** [comment]
好像还会出现，我更新后好像前几天又成480P（不确定）,不过昨天碰巧把uwp的所有数据清了，今天早上刚登陆，如果变回480p我会及时来反馈的

**Comment by ywmoyue** [comment]
分辨率问题可能是Cookie被其他垃圾清理软件删除导致的，已在4.6.10处理，此issue改为仅处理记录视频播放进度问题

**Comment by Ye-QAQ** [comment]
果然没有复现咧，感谢ywmoyue的，修复👍💕💕💕💕💕
