### ISSUE TITLE
动态评论区UI bug 和单窗口模式显示bug

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#875]
### Bug 描述

出现透明背景导致的文字重叠情况

### 操作步骤

```plain text
在动态中点击任意评论区即可复现
```

### 期望结果

正常显示

### 截图

![image](https://github.com/user-attachments/assets/2af34347-eb3c-499a-9352-70e6cab8417a)

### 应用来源

Github/其他Github镜像站

### 备注

使用最新commit构建 可能和 #871 有关?

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
感谢反馈

**Comment by ProJend** [comment]
已复现
