### ISSUE TITLE
个人空间页动态评论背景透明问题

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#888]

**Comment by ProJend** [comment]
@ywmoyue 我已经修好了

**Comment by ywmoyue** [comment]
> @ywmoyue 我已经修好了

好的，非常感谢，您可以新开一个分支提交PR

**Comment by ywmoyue** [comment]
https://github.com/ywmoyue/biliuwp-lite/discussions/892
