### ISSUE TITLE
biliuwp4.7.6版本详情页透明化

### ISSUE THREAD

**Issue by KennethWuWu** [ywmoyue/biliuwp-lite#910]
### Bug 描述

视频详情页透明化，无法正常浏览详情页信息。

### 操作步骤

```plain text
1.打开biliuwp4.7.4.702
2.点开任意视频
3.点击视频右下角“详情”按钮，发现页面透明化。
4.使用设备：lenovo yoga tablet 851（1051）f
5.系统版本：win10 22h2 build：19045.5011
```

### 期望结果

详情页恢复正常

### 截图

![mmexport1731049341214](https://github.com/user-attachments/assets/21038f6a-7dfe-4663-ae20-fe33f085238d)
![mmexport1731049339043](https://github.com/user-attachments/assets/4778f549-0afd-4e73-9678-9625ceb57f09)

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

其它 (需注明)

### 其它系统版本

windows10 22h2 build:19045.5011

### 设备类型

平板

### 设备架构

x86

### 应用架构

x86

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
好的，复现了，感谢反馈
