### ISSUE TITLE
倍速播放卡顿问题

### ISSUE THREAD

**Issue by Yur1et** [ywmoyue/biliuwp-lite#918]
### 问题描述

官方客户端的长按右键倍速播放在启停时，不会出现视频播放卡顿掉帧等情况，但本客户端时常出现卡顿以及视频回滚。不知道是不是播放器的缺陷。

### 描述解决方案

推出自选播放器或者优化快进体验

### 代码贡献

否

**Comment by ywmoyue** [comment]
![image](https://github.com/user-attachments/assets/eb004757-634d-4e1f-8fb4-fb0946ef2704)

@Yur1et 现在支持选择Native和FFmpegInterop播放器，请问你现在用的哪一个

**Comment by Yur1et** [comment]
您好，我从Native切换到ffmpeg后卡顿情况明显有所改善。但每次按下方向右键都会闪过“缓冲中”的字样。不过基本不影响使用。非常感谢
