### ISSUE TITLE
深色模式下背景色似乎有些偏亮

### ISSUE THREAD

**Issue by LOGYT-Eberk** [ywmoyue/biliuwp-lite#92]
对比了一下系统界面的深色模式，发现这个版本的背景色有点偏亮，观感不是很好。是否能稍微调暗一些？

![image](https://github.com/ywmoyue/biliuwp-lite/assets/117907349/749e3f37-1eff-4ead-b7b6-1c6240b4c668)

**Comment by zcq15** [comment]
![屏幕截图 2023-05-10 205406](https://github.com/ywmoyue/biliuwp-lite/assets/20285324/815b2637-eea3-44f9-8cce-92a5545888fe)
都是深色，你这颜色和我的看起来很不一样

**Comment by TPAXcc** [comment]
> ![屏幕截图 2023-05-10 205406](https://user-images.githubusercontent.com/20285324/237396771-815b2637-eea3-44f9-8cce-92a5545888fe.png) 都是深色，你这颜色和我的看起来很不一样

Same, 感觉不是App的问题，我也没那么亮

**Comment by ywmoyue** [comment]
似乎单窗口模式是要比标签页模式亮不少，我研究下
