### ISSUE TITLE
缺少合适的数字证书

### ISSUE THREAD

**Issue by ProJend** [ywmoyue/biliuwp-lite#924]
### 问题描述

不能根据所提供的指纹xxxxxxxxx找到证书

### 描述解决方案

请预留一个合适的临时数字证书以便辅助开发
![屏幕截图 2024-11-23 003038](https://github.com/user-attachments/assets/e87cfe52-8c9f-40c3-a3e0-517186ac3630)

### 代码贡献

否

**Comment by GD-Slime** [comment]
我在本地开发时直接用自己的证书替换了，只需在commit时不把证书提交就行了
希望可以帮到你
