### ISSUE TITLE
直播间互动区自动清理无效

### ISSUE THREAD

**Issue by GuaiYiHu** [ywmoyue/biliuwp-lite#938]
### Bug 描述

直播间右上设置了互动区自动清理，发现并不会自动清理

### 操作步骤

```plain text
1. 直播间设置自动清理条数
2. 右边互动区不会自动清理
```

### 期望结果

期望超过条数自动清理

### 截图

![屏幕截图(3)](https://github.com/user-attachments/assets/d2e35081-f3d0-4aea-9d57-62c8c5c2ba60)

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
这是因为自动清理的触发时机是在接收弹幕后触发，其他交互消息不会触发
