### ISSUE TITLE
下载视频页优化

### ISSUE THREAD

**Issue by ywmoyue** [ywmoyue/biliuwp-lite#939]
### Discussed in https://github.com/ywmoyue/biliuwp-lite/discussions/745

1. 添加一键清除搜索结果按钮
2. 添加排序选项

**Comment by lyppiao** [comment]
这个排序的选项，可以把初始的选项，由默认改为时间倒序吗？
或者新增个”自定义默认排序方式”的功能选项也可以，但是感觉没有太大必要，直接简单修改下初始选项就很实用了。
时间倒序肯定是最实用的选项，希望可以一打开就是这个。默认跟乱序基本没有区别，找东西根本找不到，最不实用的就是这个。

另外打开下载页的时候，能不能做一个优先级判定，不要每次都进正在下载的页面。
逻辑大概是：当前正在下载视频时，默认进正在下载的页面。当前没有在下载视频，就直接进入下载完成的页面。
