### ISSUE TITLE
能否添加支持视频章节分段

### ISSUE THREAD

**Issue by sharkucn** [ywmoyue/biliuwp-lite#962]
### 问题描述

便于跳过片头、快速定位感兴趣部分等操作。

### 描述解决方案

类似网页端控件，在进度条添加分段显示、视频时长右侧添加展开菜单
![W2E~JG(`@$ZF235VCGEJ{3C](https://github.com/user-attachments/assets/104ca488-846e-4983-8955-c7bd87d422c6)

### 代码贡献

否

**Comment by ywmoyue** [comment]
4.7.4+已支持 https://github.com/ywmoyue/biliuwp-lite/issues/822

![image](https://github.com/user-attachments/assets/1a462098-6977-4835-b94a-47eb7b990c02)
